import type { EventType, PuppyEvent } from './domain';
import type { ThemeVoice } from './theme';

export type AppLanguage = 'en' | 'zh-Hans' | 'es';
export type LanguagePreference = 'system' | AppLanguage;

export const languageChoices: readonly LanguagePreference[] = ['system', 'en', 'zh-Hans', 'es'];

const english = {
  'language.system': 'System',
  'language.systemDetail': 'Follow this device',
  'language.en': 'English',
  'language.zh-Hans': 'Simplified Chinese',
  'language.es': 'Spanish',
  'nav.log': 'Today',
  'nav.timeline': 'Timeline',
  'nav.insights': 'Insights',
  'nav.schedule': 'Schedule',
  'appearance.title': 'Choose an appearance',
  'appearance.subtitle': '10 visual styles, each with its own voice and icons.',
  'appearance.themeHeading': 'THEME',
  'appearance.languageHeading': 'LANGUAGE',
  'appearance.languageHint': 'Language is saved separately from the visual theme.',
  'appearance.close': 'Close appearance picker',
  'theme.meadow.detail': 'Soft journal · relaxed',
  'theme.sunrise.detail': 'Crisp checklist · compact',
  'theme.midnight.detail': 'Floating cards · spacious',
  'theme.paper.detail': 'Monochrome notebook · square',
  'theme.bubblegum.detail': 'Playful bubbles · chunky',
  'theme.blueprint.detail': 'Technical grid · dense',
  'theme.trail.detail': 'Rugged cards · sturdy',
  'theme.tide.detail': 'Airy capsules · calm',
  'theme.plum.detail': 'Editorial blocks · dramatic',
  'theme.contrast.detail': 'Bold outlines · maximum clarity',
  'event.pee': 'Pee',
  'event.poop': 'Poop',
  'event.meal': 'Ate',
  'event.pottyTrip': 'Potty trip',
  'event.walk': 'Walk',
  'event.nap': 'Nap',
  'event.custom': 'Other',
  'eventPast.pee': 'Peed',
  'eventPast.poop': 'Pooped',
  'eventPast.meal': 'Ate a meal',
  'eventPast.pottyTrip': 'Went out for potty',
  'eventPast.walk': 'Went for a walk',
  'eventPast.nap': 'Started a nap',
  'eventPast.custom': 'Other activity',
  'eventPast.napRunning': 'Nap in progress',
  'eventPast.napped': 'Napped',
  'time.justNow': 'just now',
  'time.minutes': '{count}m',
  'time.hours': '{count}h',
  'time.days': '{count}d',
  'time.minutesAgo': '{count}m ago',
  'time.hoursAgo': '{count}h ago',
  'time.daysAgo': '{count}d ago',
  'quick.endNap': 'End nap',
  'quick.endNapA11y': 'End the current nap',
  'quick.endNapHint': 'Saves the nap end time',
  'quick.logAction': 'Log {activity}',
  'quick.logHint': 'Adds the current time to the activity log',
  'quick.running': '{time} running',
  'quick.notYet': 'Not yet',
  'quick.another': 'Another activity',
  'quick.anotherHint': 'Opens common and custom activities',
  'quick.logAnother': 'Log another activity',
  'quick.commonChoices': 'Common choices stay one tap away.',
  'quick.customActivity': 'CUSTOM ACTIVITY',
  'quick.customPlaceholder': 'e.g. Grooming',
  'quick.customName': 'Custom activity name',
  'quick.customLogA11y': 'Log custom activity now',
  'quick.logNow': 'Log now',
  'quick.close': 'Close activity picker',
  'quick.water': 'Water',
  'quick.accident': 'Accident',
  'quick.play': 'Play',
  'quick.training': 'Training',
  'quick.crate': 'Crate',
  'quick.medicine': 'Medicine',
  'routine.eyebrow': 'TODAY’S RHYTHM',
  'routine.build': 'Build a daily rhythm',
  'routine.buildDetail': 'Add the times you want to repeat each day.',
  'routine.due': '{activity} is due',
  'routine.at': '{activity} at {time}',
  'routine.missedOne': '1 routine window needs attention',
  'routine.missedMany': '{count} routine windows need attention',
  'routine.complete': 'Today’s routine is complete',
  'routine.plannedFor': 'Planned for {time}',
  'routine.inMinutes': 'in {count}m',
  'routine.inHours': 'in {count}h',
  'routine.inHoursMinutes': 'in {hours}h {minutes}m',
  'routine.now': 'now',
  'routine.progress': '{completed} of {total} done',
  'routine.logged': '{completed} of {total} planned activities logged',
  'routine.openHint': 'Opens the daily schedule',
  'common.undo': 'Undo',
  'common.addNote': 'Add note',
  'common.addNoteA11y': 'Add a note to this log',
  'common.done': 'Done',
  'eventRow.now': 'now',
  'eventRow.running': 'running',
  'eventRow.widget': 'Widget',
  'eventRow.app': 'App',
  'eventRow.edit': 'Edit {activity} log',
  'eventRow.editNapHint': 'Opens date, time, and note controls',
  'eventRow.editHint': 'Opens activity, date, time, and note controls',
  'eventRow.delete': 'Delete {activity} at {time}',
  'note.listeningAnnouncement': 'Listening for note',
  'note.transcribeErrorTitle': 'Couldn’t transcribe that',
  'note.accessOff': 'Microphone or speech access is off. You can enable it in Settings, or type the note instead.',
  'note.tryAgain': 'Try the microphone again, or type the note instead.',
  'note.unavailableTitle': 'Voice notes unavailable',
  'note.unavailableBody': 'Speech recognition is not available on this phone. You can still type the note.',
  'note.permissionTitle': 'Microphone access needed',
  'note.permissionBody': 'Allow microphone and speech access to dictate notes. You can still type the note.',
  'note.startError': 'The speech recognizer could not start. You can still type the note.',
  'note.label': 'Note for this log',
  'note.placeholder': 'e.g. Just after a play session',
  'note.stopDictating': 'Stop dictating note',
  'note.dictate': 'Dictate note',
  'note.listeningHint': 'Listening… Tap stop when you’re done.',
  'note.idleHint': 'Type a note or tap the microphone to dictate.',
  'log.customizeWidgetA11y': 'Customize home-screen widget',
  'log.changeAppearanceA11y': 'Change appearance and language',
  'log.activity': 'Activity',
  'log.totalCount': '{count} total',
  'log.recentCount': '{count} recent',
  'log.filter.all': 'All',
  'log.filter.potty': 'Potty',
  'log.filter.meals': 'Meals',
  'log.filter.walks': 'Walks',
  'log.filter.naps': 'Naps',
  'log.filter.other': 'Other',
  'log.showFilter': 'Show {filter} activity',
  'log.showRecentA11y': 'Show activity from the last {count} days',
  'log.viewAllA11y': 'View all activity history, including {count} older logs',
  'log.showRecent': 'Show recent {count} days',
  'log.viewAll': 'View all history',
  'log.recentDetail': 'Return to the activity that matters most now',
  'log.olderDetail': '{count} older logs grouped by month',
  'log.today': 'Today',
  'log.yesterday': 'Yesterday',
  'log.emptyTitle': 'Your log starts here',
  'log.emptyFilteredTitle': 'No {filter} logged',
  'log.emptyBody': 'Tap an action above when it happens.',
  'log.emptyFilteredBody': 'Choose another filter or log an activity above.',
  'log.saveErrorTitle': 'Couldn’t save changes',
  'log.saveErrorBody': 'Keep the editor open and tap the save status to try again.',
  'log.widgetErrorTitle': 'Couldn’t save widget settings',
  'log.tryAgain': 'Try again.',
  'editor.editNap': 'Edit nap',
  'editor.editLog': 'Edit log',
  'editor.napSubtitle': '{activity} · Correct the timing or note.',
  'editor.logSubtitle': '{activity} · Correct the activity, timing, or note.',
  'editor.close': 'Close log editor',
  'editor.retryA11y': 'Couldn’t save changes. Retry now',
  'editor.retry': 'Couldn’t save. Tap to retry.',
  'editor.customNameStatus': 'Add a custom name to save this activity.',
  'editor.saving': 'Saving changes…',
  'editor.saved': 'Saved automatically',
  'editor.autoSave': 'Changes save automatically',
  'editor.activity': 'ACTIVITY',
  'editor.changeActivity': 'Change activity to {activity}',
  'editor.customName': 'CUSTOM NAME',
  'editor.customNameA11y': 'Custom activity name',
  'editor.customNameHint': 'Required. Changes save automatically after you type.',
  'editor.customPlaceholder': 'e.g. Grooming',
  'editor.customInvalid': 'Enter an activity name.',
  'editor.customValid': 'Use a short name you’ll recognize in the log.',
  'editor.now': 'now',
  'editor.inProgress': 'in progress',
  'editor.start': 'START',
  'editor.end': 'END',
  'editor.date': 'date',
  'editor.time': 'time',
  'editor.editNapTime': 'Edit nap {field} time',
  'editor.quickBackdate': 'QUICK BACKDATE',
  'editor.setField': 'SET {field}',
  'editor.backdate': 'Set time to {count} minutes ago',
  'editor.setNow': 'Set time to now',
  'editor.minutesAgo': '{count}m ago',
  'editor.dateTime': 'DATE & TIME',
  'editor.chooseDate': 'Choose {field} date, currently {date}',
  'editor.chooseTime': 'Choose exact {field} time, currently {time}',
  'editor.finishPicker': 'Finish choosing {picker}',
  'editor.note': 'NOTE',
  'widget.title': 'Customize widget',
  'widget.subtitle': 'Choose 2–4 actions. Small widgets show them in one row.',
  'widget.close': 'Close widget settings',
  'widget.actions': 'WIDGET ACTIONS · {count} OF 4',
  'widget.addAction': 'Add {activity} to the widget',
  'widget.removeAction': 'Remove {activity} from the widget',
  'widget.keepTwo': 'Keep at least two widget actions.',
  'widget.removeFirst': 'Remove another action first.',
  'widget.napHint': 'Nap stays available while a nap is running, even if you hide it from the default set.',
  'widget.save': 'Save widget settings',
  'common.saving': 'Saving…',
  'app.napEnded': 'Nap ended',
  'app.napStarted': 'Nap started',
  'app.logged': '{activity} logged',
  'app.estimateAdded': '{activity} added at estimated time',
  'app.deleteTitle': 'Delete this log?',
  'app.deleteMessage': '{activity} at {time}',
  'app.cancel': 'Cancel',
  'app.delete': 'Delete',
  'app.routineSaved': 'Routine saved',
  'app.notificationsOff': 'Notifications are off, so reminders could not be scheduled.',
  'app.reminderError': 'Puptime could not update reminders. Try editing the routine again.',
  'schedule.eyebrow': 'DAILY ROUTINE',
  'schedule.title': 'Make the day predictable',
  'schedule.subtitle': 'Start from patterns in your logs or edit times yourself. This is routine planning, not veterinary guidance.',
  'schedule.status.logged': 'Logged',
  'schedule.status.due': 'Due now',
  'schedule.status.missed': 'Missed',
  'schedule.status.upcoming': 'Upcoming',
  'schedule.saveErrorTitle': 'Couldn’t save the routine',
  'schedule.saveErrorBody': 'Your previous routine is still available. Please try again.',
  'schedule.notificationsOff': 'Notifications are off',
  'schedule.notificationsBody': 'Allow Puptime notifications in system settings to use daily routine reminders.',
  'schedule.notNow': 'Not now',
  'schedule.openSettings': 'Open settings',
  'schedule.reminderErrorTitle': 'Couldn’t enable reminders',
  'schedule.reminderErrorBody': 'Please try again from this routine entry.',
  'schedule.removeTitle': 'Remove this time?',
  'schedule.entryAt': '{activity} at {time}',
  'schedule.remove': 'Remove',
  'schedule.removeErrorTitle': 'Couldn’t remove the time',
  'schedule.removeErrorBody': 'Your routine has not changed. Please try again.',
  'schedule.suggestionErrorTitle': 'Couldn’t use the suggested routine',
  'schedule.suggestionErrorBody': 'Your current routine is still available. Please try again.',
  'schedule.learnTitle': 'Build from your logs',
  'schedule.learnBody': 'Finds activities that recur on most recorded days and rounds their typical times to 15 minutes.',
  'schedule.suggestedTimes': '{count} suggested times from {days} recorded days',
  'schedule.needDays': 'Log activity on {count} more days to find a routine',
  'schedule.noPattern': 'No repeated daily pattern is clear yet—keep logging',
  'schedule.previewA11y': 'Preview {count} suggested routine times',
  'schedule.notEnoughA11y': 'Not enough repeated logs to suggest a routine',
  'schedule.previewButton': 'Preview suggested routine',
  'schedule.keepLogging': 'Keep logging to unlock',
  'schedule.todaySoFar': 'TODAY SO FAR',
  'schedule.loggedProgress': '{completed} of {total} logged',
  'schedule.dueOne': '1 activity is due now',
  'schedule.dueMany': '{count} activities are due now',
  'schedule.missedOne': '1 missed window',
  'schedule.missedMany': '{count} missed windows',
  'schedule.everythingLogged': 'Everything planned has been logged',
  'schedule.nextAhead': 'The next activity is still ahead',
  'schedule.windowHint': 'A log counts on time within 30 minutes of its planned time.',
  'schedule.todayPlan': 'Today’s plan',
  'schedule.timeCount': '{count} times',
  'schedule.emptyTitle': 'No planned times',
  'schedule.emptyBody': 'Add the moments you want to repeat each day.',
  'schedule.editA11y': 'Edit {activity} at {time}, {status}{reminder}',
  'schedule.reminderOn': ', daily reminder on',
  'schedule.removeA11y': 'Remove {activity} at {time}',
  'schedule.addA11y': 'Add a routine time',
  'schedule.addTime': 'Add a time',
  'schedule.suggestionTitle': 'Routine from your logs',
  'schedule.suggestionSubtitle': 'Based on {days} recorded days from the last {period}. Review every time before using it.',
  'schedule.closeSuggestion': 'Close suggested routine',
  'schedule.replaceCurrent': 'Using this replaces your {count} current times. ',
  'schedule.createRoutine': 'Using this creates your routine. ',
  'schedule.remindersStayOff': 'Reminders stay off until you enable them on individual times.',
  'schedule.usingRoutine': 'Using routine…',
  'schedule.useRoutine': 'Use this routine',
  'schedule.keepRoutine': 'Keep current routine',
  'schedule.editTime': 'Edit time',
  'schedule.close': 'Close',
  'schedule.activity': 'ACTIVITY',
  'schedule.time': 'TIME',
  'schedule.change': 'Change',
  'schedule.reminder': 'REMINDER',
  'schedule.dailyReminder': 'Daily reminder',
  'schedule.reminderHint': 'Alerts at this planned time on this device.',
  'schedule.reminderA11y': 'Daily reminder for this routine entry',
  'schedule.saveTime': 'Save time',
  'insights.activity': 'activity',
  'insights.selectedActivity': 'selected activity',
  'insights.noSelected': 'No activities selected',
  'insights.allActivity': 'All activity',
  'insights.timing': '{activities} timing',
  'insights.activityCount': '{count} activities',
  'insights.pointWindow': '{activity} in the {start} to {end} window',
  'insights.durationWindow': '{activity} from about {start} to {end}',
  'insights.perDay': '{value}/day',
  'insights.eachRecordedDay': '{count} on each recorded day',
  'insights.rangePerDay': '{minimum}–{maximum} per recorded day',
  'insights.noLogsYet': 'No {activity} logs yet',
  'insights.needAnotherLog': 'Need another log',
  'insights.middleHalf': 'Middle half: {lower}–{upper}',
  'insights.gapsObserved': '{count} gaps observed',
  'insights.logCount': '{count} logs',
  'insights.averageFrequency': 'AVERAGE FREQUENCY',
  'insights.typicalGap': 'TYPICAL GAP',
  'insights.noLogged': 'No {activity} logged',
  'insights.noActivitySelected': 'No activity selected',
  'insights.today': 'TODAY',
  'insights.currentTime': 'Current time {time}',
  'insights.decrease': 'Decrease {control}',
  'insights.increase': 'Increase {control}',
  'insights.thisMonth': 'This month',
  'insights.monthA11y': '{month}. {average} {activity} logs per recorded day. {logs} logs across {days} recorded days.',
  'insights.monthDetail': '{logs} logs · {days} days with activity',
  'insights.exportErrorTitle': 'Couldn’t export activity',
  'insights.exportErrorBody': 'Please try again. Your Puptime data is unchanged.',
  'insights.estimateErrorTitle': 'Couldn’t add this estimate',
  'insights.estimateErrorBody': 'Your activity history is unchanged. Please try again.',
  'insights.eyebrow': 'PATTERNS FROM YOUR LOGS',
  'insights.title': 'A clearer routine',
  'insights.subtitle': 'Frequency, possible gaps, and longer-term context from what you recorded.',
  'insights.frequencyTitle': 'Frequency from your logs',
  'insights.frequencyCaption': 'Last {period} days · {recorded} days with activity · observations, not goals',
  'insights.frequencyNote': 'Daily averages include zeroes on days where you logged something else. Completely blank days are excluded because they may be unlogged.',
  'insights.gapsTitle': 'Possible gaps',
  'insights.gapsCaption': 'Repeated times from {count} active days',
  'insights.gapsNote': 'A suggestion appears only when the same activity was logged near that time on at least 3 other days and logging continued afterward. Nothing is added automatically.',
  'insights.mealName': 'Meal',
  'insights.around': 'around {time}',
  'insights.aboutRange': 'about {start}–{end}',
  'insights.possibleNap': 'Possible unlogged nap',
  'insights.mayBeUnlogged': '{activity} may be unlogged',
  'insights.seenEvidence': 'Seen near this time on {observed} of {compared} other active days.',
  'insights.addEstimateA11y': 'Add {activity} at the estimated time',
  'insights.adding': 'Adding…',
  'insights.addLog': 'Add log',
  'insights.needGapDays': 'Log activity on {count} more days to check for gaps.',
  'insights.noGaps': 'No strong gaps found in the last {count} days.',
  'insights.timelineActivities': 'Timeline activities',
  'insights.selectCombination': 'Select any combination',
  'insights.all': 'All',
  'insights.clearFilters': 'Clear all activity filters',
  'insights.selectFilters': 'Select all activity filters',
  'insights.hideTiming': 'Hide {activity} timing',
  'insights.showTiming': 'Show {activity} timing',
  'insights.panelCaption': '{range} · {count} logs · oldest at top',
  'insights.timeWidth': 'Time width',
  'insights.dayHeight': 'Days shown',
  'insights.zoomHint': 'Show more days to zoom out vertically. Enlarge the time width, then swipe sideways to inspect busy periods.',
  'insights.showEarlier': 'Show earlier dates',
  'insights.earlier': 'Earlier',
  'insights.latestDays': 'Latest {count} days',
  'insights.olderWindow': 'Older {count}-day window',
  'insights.showNewer': 'Show newer dates',
  'insights.newer': 'Newer',
  'insights.chooseActivity': 'Choose at least one activity above to show it on the timeline.',
  'insights.noRangeLogs': 'No {activity} logged in this date range.',
  'insights.historyTitle': 'Month-by-month context',
  'insights.historyCaption': 'All activity · newest month first',
  'insights.historyNote': 'Monthly pace uses days where you recorded any activity, so incomplete or missed months are not treated as zeroes.',
  'insights.showRecentMonths': 'Show recent months',
  'insights.showAllMonths': 'Show all {count} months',
  'insights.dataTitle': 'Your data',
  'insights.dataBody': 'Share every log as a spreadsheet-ready CSV. Nothing leaves this device until you choose where to send it.',
  'insights.exportA11y': 'Export all activity as CSV',
  'insights.noExport': 'No activity to export',
  'insights.exportHint': 'Opens the system share sheet',
  'insights.preparingExport': 'Preparing export…',
  'insights.exportButton': 'Export activity CSV',
  'timeline.eyebrow': 'DAILY RHYTHM · 15 MINUTE WINDOWS',
  'timeline.title': 'When things happen',
  'timeline.subtitle': 'Scroll up for earlier days. Pinch or use the buttons to expand time.',
  'timeline.date': 'DATE',
  'timeline.zoomOut': 'Zoom out time',
  'timeline.zoomIn': 'Zoom in time',
  'timeline.range': '{range} · {count} logs',
  'timeline.pinchHint': 'Pinch to expand time',
  'timeline.loadEarlier': 'Load earlier days',
  'timeline.loadingEarlier': 'Loading earlier days',
  'timeline.historyStart': 'No earlier logged days',
  'voice.gentle.eyebrow': 'PUPTIME · {date}',
  'voice.gentle.title': 'What just happened?',
  'voice.gentle.subtitle': 'One tap keeps your pup’s day close at hand.',
  'voice.brisk.eyebrow': 'QUICK LOG · {date}',
  'voice.brisk.title': 'Log it while it’s fresh',
  'voice.brisk.subtitle': 'Fast taps now, clean timeline later.',
  'voice.quiet.eyebrow': 'DAILY LOG · {date}',
  'voice.quiet.title': 'Add to today',
  'voice.quiet.subtitle': 'A quiet record of meals, walks, naps, and more.',
  'voice.notebook.eyebrow': 'DAILY NOTES · {date}',
  'voice.notebook.title': 'Write down the moment',
  'voice.notebook.subtitle': 'A simple line now keeps the whole day legible.',
  'voice.playful.eyebrow': 'PUP CHECK-IN · {date}',
  'voice.playful.title': 'What did your pup get up to?',
  'voice.playful.subtitle': 'Tap it now—you can add the story later.',
  'voice.technical.eyebrow': 'ACTIVITY CONSOLE · {date}',
  'voice.technical.title': 'Record an event',
  'voice.technical.subtitle': 'Timestamp the activity now; refine it later.',
  'voice.outdoors.eyebrow': 'FIELD LOG · {date}',
  'voice.outdoors.title': 'Mark the trail',
  'voice.outdoors.subtitle': 'Keep today’s stops, walks, and rest in view.',
  'voice.calm.eyebrow': 'DAILY FLOW · {date}',
  'voice.calm.title': 'Capture the rhythm',
  'voice.calm.subtitle': 'A gentle tap keeps the day moving.',
  'voice.editorial.eyebrow': 'THE DAILY EDITION · {date}',
  'voice.editorial.title': 'Today, in motion',
  'voice.editorial.subtitle': 'Add the latest moment to the record.',
  'voice.direct.eyebrow': 'QUICK LOG · {date}',
  'voice.direct.title': 'Choose an action',
  'voice.direct.subtitle': 'One tap records the current time.',
} as const;

export type MessageKey = keyof typeof english;
type Dictionary = Record<MessageKey, string>;

const simplifiedChinese: Dictionary = {
  'language.system': '跟随系统',
  'language.systemDetail': '使用此设备的语言',
  'language.en': '英语',
  'language.zh-Hans': '简体中文',
  'language.es': '西班牙语',
  'nav.log': '今天',
  'nav.timeline': '时间线',
  'nav.insights': '分析',
  'nav.schedule': '日程',
  'appearance.title': '选择外观',
  'appearance.subtitle': '10 种视觉风格，各有自己的语气和图标。',
  'appearance.themeHeading': '主题',
  'appearance.languageHeading': '语言',
  'appearance.languageHint': '语言与视觉主题分别保存。',
  'appearance.close': '关闭外观选择器',
  'theme.meadow.detail': '柔和手帐 · 松弛',
  'theme.sunrise.detail': '清爽清单 · 紧凑',
  'theme.midnight.detail': '悬浮卡片 · 宽松',
  'theme.paper.detail': '黑白笔记 · 方正',
  'theme.bubblegum.detail': '活泼泡泡 · 圆润',
  'theme.blueprint.detail': '技术蓝图 · 密集',
  'theme.trail.detail': '户外卡片 · 稳重',
  'theme.tide.detail': '轻盈胶囊 · 平静',
  'theme.plum.detail': '编辑版式 · 醒目',
  'theme.contrast.detail': '粗体轮廓 · 清晰优先',
  'event.pee': '尿尿',
  'event.poop': '便便',
  'event.meal': '吃饭',
  'event.pottyTrip': '外出如厕',
  'event.walk': '散步',
  'event.nap': '小睡',
  'event.custom': '其他',
  'eventPast.pee': '尿尿了',
  'eventPast.poop': '便便了',
  'eventPast.meal': '吃过饭',
  'eventPast.pottyTrip': '外出如厕了',
  'eventPast.walk': '散过步',
  'eventPast.nap': '开始小睡',
  'eventPast.custom': '其他活动',
  'eventPast.napRunning': '正在小睡',
  'eventPast.napped': '睡了一觉',
  'time.justNow': '刚刚',
  'time.minutes': '{count} 分钟',
  'time.hours': '{count} 小时',
  'time.days': '{count} 天',
  'time.minutesAgo': '{count} 分钟前',
  'time.hoursAgo': '{count} 小时前',
  'time.daysAgo': '{count} 天前',
  'quick.endNap': '结束小睡',
  'quick.endNapA11y': '结束当前小睡',
  'quick.endNapHint': '保存小睡结束时间',
  'quick.logAction': '记录{activity}',
  'quick.logHint': '把当前时间添加到活动记录',
  'quick.running': '已进行 {time}',
  'quick.notYet': '尚未记录',
  'quick.another': '其他活动',
  'quick.anotherHint': '打开常用和自定义活动',
  'quick.logAnother': '记录其他活动',
  'quick.commonChoices': '常用项目，一点即记。',
  'quick.customActivity': '自定义活动',
  'quick.customPlaceholder': '例如：梳毛',
  'quick.customName': '自定义活动名称',
  'quick.customLogA11y': '立即记录自定义活动',
  'quick.logNow': '立即记录',
  'quick.close': '关闭活动选择器',
  'quick.water': '喝水',
  'quick.accident': '意外',
  'quick.play': '玩耍',
  'quick.training': '训练',
  'quick.crate': '进笼',
  'quick.medicine': '吃药',
  'routine.eyebrow': '今日节奏',
  'routine.build': '建立每日节奏',
  'routine.buildDetail': '添加每天想重复的时间点。',
  'routine.due': '该进行{activity}了',
  'routine.at': '{time} · {activity}',
  'routine.missedOne': '有 1 个日程时间需要留意',
  'routine.missedMany': '有 {count} 个日程时间需要留意',
  'routine.complete': '今天的日程已完成',
  'routine.plannedFor': '计划时间 {time}',
  'routine.inMinutes': '{count} 分钟后',
  'routine.inHours': '{count} 小时后',
  'routine.inHoursMinutes': '{hours} 小时 {minutes} 分钟后',
  'routine.now': '现在',
  'routine.progress': '已完成 {completed}/{total}',
  'routine.logged': '已记录 {completed}/{total} 项计划活动',
  'routine.openHint': '打开每日日程',
  'common.undo': '撤销',
  'common.addNote': '添加备注',
  'common.addNoteA11y': '为这条记录添加备注',
  'common.done': '完成',
  'eventRow.now': '现在',
  'eventRow.running': '进行中',
  'eventRow.widget': '小组件',
  'eventRow.app': '应用',
  'eventRow.edit': '编辑{activity}记录',
  'eventRow.editNapHint': '打开日期、时间和备注控件',
  'eventRow.editHint': '打开活动、日期、时间和备注控件',
  'eventRow.delete': '删除 {time} 的{activity}记录',
  'note.listeningAnnouncement': '正在聆听备注',
  'note.transcribeErrorTitle': '无法转写',
  'note.accessOff': '麦克风或语音权限已关闭。你可以在设置中开启，或直接输入备注。',
  'note.tryAgain': '请重试麦克风，或直接输入备注。',
  'note.unavailableTitle': '语音备注不可用',
  'note.unavailableBody': '此手机不支持语音识别，你仍可输入备注。',
  'note.permissionTitle': '需要麦克风权限',
  'note.permissionBody': '请允许麦克风和语音权限来听写备注，你仍可输入备注。',
  'note.startError': '语音识别无法启动，你仍可输入备注。',
  'note.label': '此记录的备注',
  'note.placeholder': '例如：刚玩耍结束',
  'note.stopDictating': '停止听写备注',
  'note.dictate': '听写备注',
  'note.listeningHint': '正在聆听…完成后请点停止。',
  'note.idleHint': '输入备注，或点麦克风开始听写。',
  'log.customizeWidgetA11y': '自定义主屏幕小组件',
  'log.changeAppearanceA11y': '更改外观和语言',
  'log.activity': '活动',
  'log.totalCount': '共 {count} 条',
  'log.recentCount': '最近 {count} 条',
  'log.filter.all': '全部',
  'log.filter.potty': '如厕',
  'log.filter.meals': '吃饭',
  'log.filter.walks': '散步',
  'log.filter.naps': '小睡',
  'log.filter.other': '其他',
  'log.showFilter': '显示{filter}活动',
  'log.showRecentA11y': '显示最近 {count} 天的活动',
  'log.viewAllA11y': '查看全部活动记录，包括 {count} 条更早的记录',
  'log.showRecent': '显示最近 {count} 天',
  'log.viewAll': '查看全部记录',
  'log.recentDetail': '返回当前最相关的活动',
  'log.olderDetail': '按月份整理的 {count} 条更早记录',
  'log.today': '今天',
  'log.yesterday': '昨天',
  'log.emptyTitle': '从这里开始记录',
  'log.emptyFilteredTitle': '还没有{filter}记录',
  'log.emptyBody': '活动发生时，点一下上方动作即可。',
  'log.emptyFilteredBody': '选择其他筛选项，或在上方记录活动。',
  'log.saveErrorTitle': '无法保存更改',
  'log.saveErrorBody': '请保持编辑器打开，并点保存状态重试。',
  'log.widgetErrorTitle': '无法保存小组件设置',
  'log.tryAgain': '请重试。',
  'editor.editNap': '编辑小睡',
  'editor.editLog': '编辑记录',
  'editor.napSubtitle': '{activity} · 修改时间或备注。',
  'editor.logSubtitle': '{activity} · 修改活动、时间或备注。',
  'editor.close': '关闭记录编辑器',
  'editor.retryA11y': '无法保存更改，立即重试',
  'editor.retry': '无法保存，点此重试。',
  'editor.customNameStatus': '添加自定义名称后才能保存。',
  'editor.saving': '正在保存更改…',
  'editor.saved': '已自动保存',
  'editor.autoSave': '更改会自动保存',
  'editor.activity': '活动',
  'editor.changeActivity': '将活动改为{activity}',
  'editor.customName': '自定义名称',
  'editor.customNameA11y': '自定义活动名称',
  'editor.customNameHint': '必填。输入后会自动保存更改。',
  'editor.customPlaceholder': '例如：梳毛',
  'editor.customInvalid': '请输入活动名称。',
  'editor.customValid': '使用一个容易在记录中识别的简短名称。',
  'editor.now': '现在',
  'editor.inProgress': '进行中',
  'editor.start': '开始',
  'editor.end': '结束',
  'editor.date': '日期',
  'editor.time': '时间',
  'editor.editNapTime': '编辑小睡{field}时间',
  'editor.quickBackdate': '快速回溯',
  'editor.setField': '设置{field}',
  'editor.backdate': '将时间设为 {count} 分钟前',
  'editor.setNow': '将时间设为现在',
  'editor.minutesAgo': '{count} 分钟前',
  'editor.dateTime': '日期和时间',
  'editor.chooseDate': '选择{field}日期，当前为 {date}',
  'editor.chooseTime': '选择{field}准确时间，当前为 {time}',
  'editor.finishPicker': '完成选择{picker}',
  'editor.note': '备注',
  'widget.title': '自定义小组件',
  'widget.subtitle': '选择 2–4 个动作。小号组件会在一行内显示。',
  'widget.close': '关闭小组件设置',
  'widget.actions': '小组件动作 · {count}/4',
  'widget.addAction': '将{activity}添加到小组件',
  'widget.removeAction': '从小组件移除{activity}',
  'widget.keepTwo': '至少保留两个小组件动作。',
  'widget.removeFirst': '请先移除另一个动作。',
  'widget.napHint': '小睡进行时，即使默认动作中隐藏了它，也仍可使用。',
  'widget.save': '保存小组件设置',
  'common.saving': '正在保存…',
  'app.napEnded': '小睡已结束',
  'app.napStarted': '小睡已开始',
  'app.logged': '已记录{activity}',
  'app.estimateAdded': '已在推测时间添加{activity}',
  'app.deleteTitle': '删除这条记录？',
  'app.deleteMessage': '{time} · {activity}',
  'app.cancel': '取消',
  'app.delete': '删除',
  'app.routineSaved': '日程已保存',
  'app.notificationsOff': '通知已关闭，因此无法安排提醒。',
  'app.reminderError': 'Puptime 无法更新提醒。请再次编辑日程。',
  'schedule.eyebrow': '每日计划',
  'schedule.title': '让一天更有规律',
  'schedule.subtitle': '从记录中的规律开始，或自行编辑时间。这是日常规划，并非兽医建议。',
  'schedule.status.logged': '已记录',
  'schedule.status.due': '现在该做',
  'schedule.status.missed': '已错过',
  'schedule.status.upcoming': '即将到来',
  'schedule.saveErrorTitle': '无法保存日程',
  'schedule.saveErrorBody': '之前的日程仍然可用，请重试。',
  'schedule.notificationsOff': '通知已关闭',
  'schedule.notificationsBody': '请在系统设置中允许 Puptime 通知，以使用每日提醒。',
  'schedule.notNow': '暂不',
  'schedule.openSettings': '打开设置',
  'schedule.reminderErrorTitle': '无法启用提醒',
  'schedule.reminderErrorBody': '请从此日程项目中重试。',
  'schedule.removeTitle': '移除这个时间？',
  'schedule.entryAt': '{time} · {activity}',
  'schedule.remove': '移除',
  'schedule.removeErrorTitle': '无法移除时间',
  'schedule.removeErrorBody': '日程未发生变化，请重试。',
  'schedule.suggestionErrorTitle': '无法使用建议日程',
  'schedule.suggestionErrorBody': '当前日程仍然可用，请重试。',
  'schedule.learnTitle': '根据记录建立日程',
  'schedule.learnBody': '查找大多数记录日都会重复的活动，并将常见时间取整到 15 分钟。',
  'schedule.suggestedTimes': '根据 {days} 个记录日建议了 {count} 个时间',
  'schedule.needDays': '再记录 {count} 天活动即可寻找规律',
  'schedule.noPattern': '尚未发现清晰的每日规律，请继续记录',
  'schedule.previewA11y': '预览 {count} 个建议日程时间',
  'schedule.notEnoughA11y': '重复记录不足，无法建议日程',
  'schedule.previewButton': '预览建议日程',
  'schedule.keepLogging': '继续记录后解锁',
  'schedule.todaySoFar': '今天到目前为止',
  'schedule.loggedProgress': '已记录 {completed}/{total}',
  'schedule.dueOne': '现在有 1 项活动该进行了',
  'schedule.dueMany': '现在有 {count} 项活动该进行了',
  'schedule.missedOne': '错过了 1 个时间段',
  'schedule.missedMany': '错过了 {count} 个时间段',
  'schedule.everythingLogged': '所有计划项目都已记录',
  'schedule.nextAhead': '下一项活动还没到时间',
  'schedule.windowHint': '在计划时间前后 30 分钟内记录，均视为准时。',
  'schedule.todayPlan': '今日计划',
  'schedule.timeCount': '{count} 个时间',
  'schedule.emptyTitle': '没有计划时间',
  'schedule.emptyBody': '添加每天想重复的时刻。',
  'schedule.editA11y': '编辑 {time} 的{activity}，{status}{reminder}',
  'schedule.reminderOn': '，每日提醒已开启',
  'schedule.removeA11y': '移除 {time} 的{activity}',
  'schedule.addA11y': '添加日程时间',
  'schedule.addTime': '添加时间',
  'schedule.suggestionTitle': '根据记录生成的日程',
  'schedule.suggestionSubtitle': '基于最近 {period} 天中的 {days} 个记录日。使用前请逐项检查。',
  'schedule.closeSuggestion': '关闭建议日程',
  'schedule.replaceCurrent': '使用后会替换当前 {count} 个时间。',
  'schedule.createRoutine': '使用后会创建你的日程。',
  'schedule.remindersStayOff': '提醒默认关闭，可在各个时间上单独开启。',
  'schedule.usingRoutine': '正在使用日程…',
  'schedule.useRoutine': '使用此日程',
  'schedule.keepRoutine': '保留当前日程',
  'schedule.editTime': '编辑时间',
  'schedule.close': '关闭',
  'schedule.activity': '活动',
  'schedule.time': '时间',
  'schedule.change': '更改',
  'schedule.reminder': '提醒',
  'schedule.dailyReminder': '每日提醒',
  'schedule.reminderHint': '在此设备上于计划时间发出提醒。',
  'schedule.reminderA11y': '此日程项目的每日提醒',
  'schedule.saveTime': '保存时间',
  'insights.activity': '活动',
  'insights.selectedActivity': '所选活动',
  'insights.noSelected': '未选择活动',
  'insights.allActivity': '全部活动',
  'insights.timing': '{activities}时间',
  'insights.activityCount': '{count} 项活动',
  'insights.pointWindow': '{activity}出现在 {start} 到 {end} 之间',
  'insights.durationWindow': '{activity}大约从 {start} 持续到 {end}',
  'insights.perDay': '{value}/天',
  'insights.eachRecordedDay': '每个记录日 {count} 次',
  'insights.rangePerDay': '每个记录日 {minimum}–{maximum} 次',
  'insights.noLogsYet': '还没有{activity}记录',
  'insights.needAnotherLog': '还需要一条记录',
  'insights.middleHalf': '中间一半：{lower}–{upper}',
  'insights.gapsObserved': '观察到 {count} 个间隔',
  'insights.logCount': '{count} 条记录',
  'insights.averageFrequency': '平均频率',
  'insights.typicalGap': '典型间隔',
  'insights.noLogged': '未记录{activity}',
  'insights.noActivitySelected': '未选择活动',
  'insights.today': '今天',
  'insights.currentTime': '当前时间 {time}',
  'insights.decrease': '减小{control}',
  'insights.increase': '增大{control}',
  'insights.thisMonth': '本月',
  'insights.monthA11y': '{month}。每个记录日平均 {average} 条{activity}记录。{days} 个记录日共 {logs} 条。',
  'insights.monthDetail': '{logs} 条记录 · {days} 个活动日',
  'insights.exportErrorTitle': '无法导出活动',
  'insights.exportErrorBody': '请重试。Puptime 数据未发生变化。',
  'insights.estimateErrorTitle': '无法添加这条推测记录',
  'insights.estimateErrorBody': '活动历史未发生变化，请重试。',
  'insights.eyebrow': '记录中的规律',
  'insights.title': '日常节奏更清晰',
  'insights.subtitle': '从记录中查看频率、可能漏记和长期趋势。',
  'insights.frequencyTitle': '记录中的频率',
  'insights.frequencyCaption': '最近 {period} 天 · {recorded} 个活动日 · 只做观察，不设目标',
  'insights.frequencyNote': '如果当天记录了其他活动，每日平均值会计入零次。完全空白的日期会排除，因为可能只是漏记。',
  'insights.gapsTitle': '可能漏记',
  'insights.gapsCaption': '来自 {count} 个活动日的重复时间',
  'insights.gapsNote': '仅当同一活动在至少 3 个其他日期的相近时间出现，而且之后仍有记录时才会给出建议。不会自动添加任何内容。',
  'insights.mealName': '吃饭',
  'insights.around': '约 {time}',
  'insights.aboutRange': '约 {start}–{end}',
  'insights.possibleNap': '可能漏记的小睡',
  'insights.mayBeUnlogged': '可能漏记了{activity}',
  'insights.seenEvidence': '在另外 {compared} 个活动日中，有 {observed} 天在相近时间出现。',
  'insights.addEstimateA11y': '在推测时间添加{activity}',
  'insights.adding': '正在添加…',
  'insights.addLog': '添加记录',
  'insights.needGapDays': '再记录 {count} 天活动即可检查漏记。',
  'insights.noGaps': '最近 {count} 天未发现明显漏记。',
  'insights.timelineActivities': '时间线活动',
  'insights.selectCombination': '可多选',
  'insights.all': '全部',
  'insights.clearFilters': '清除全部活动筛选',
  'insights.selectFilters': '选择全部活动筛选',
  'insights.hideTiming': '隐藏{activity}时间',
  'insights.showTiming': '显示{activity}时间',
  'insights.panelCaption': '{range} · {count} 条记录 · 由旧到新',
  'insights.timeWidth': '时间宽度',
  'insights.dayHeight': '显示天数',
  'insights.zoomHint': '增加显示天数可纵向缩小；放大时间宽度后，可左右滑动图表查看活动密集时段。',
  'insights.showEarlier': '显示更早日期',
  'insights.earlier': '更早',
  'insights.latestDays': '最近 {count} 天',
  'insights.olderWindow': '更早的 {count} 天',
  'insights.showNewer': '显示较新日期',
  'insights.newer': '较新',
  'insights.chooseActivity': '请至少选择一项活动以显示在时间线上。',
  'insights.noRangeLogs': '此日期范围内没有{activity}记录。',
  'insights.historyTitle': '逐月背景',
  'insights.historyCaption': '全部活动 · 最新月份优先',
  'insights.historyNote': '月度频率仅使用有活动记录的日期，因此不完整或漏记的月份不会被当作零。',
  'insights.showRecentMonths': '显示最近月份',
  'insights.showAllMonths': '显示全部 {count} 个月',
  'insights.dataTitle': '你的数据',
  'insights.dataBody': '将全部记录分享为可供表格使用的 CSV。在你选择发送位置前，数据不会离开此设备。',
  'insights.exportA11y': '将全部活动导出为 CSV',
  'insights.noExport': '没有可导出的活动',
  'insights.exportHint': '打开系统分享面板',
  'insights.preparingExport': '正在准备导出…',
  'insights.exportButton': '导出活动 CSV',
  'timeline.eyebrow': '每日节奏 · 15 分钟窗口',
  'timeline.title': '活动通常何时发生',
  'timeline.subtitle': '向上滚动查看更早日期。双指捏合或使用按钮展开时间。',
  'timeline.date': '日期',
  'timeline.zoomOut': '缩小时间',
  'timeline.zoomIn': '放大时间',
  'timeline.range': '{range} · {count} 条记录',
  'timeline.pinchHint': '双指捏合展开时间',
  'timeline.loadEarlier': '加载更早日期',
  'timeline.loadingEarlier': '正在加载更早日期',
  'timeline.historyStart': '没有更早的记录日期',
  'voice.gentle.eyebrow': 'PUPTIME · {date}',
  'voice.gentle.title': '刚刚发生了什么？',
  'voice.gentle.subtitle': '轻点一下，就能记住狗狗一天的节奏。',
  'voice.brisk.eyebrow': '快速记录 · {date}',
  'voice.brisk.title': '趁新鲜，马上记录',
  'voice.brisk.subtitle': '现在轻松点一下，之后时间线更清楚。',
  'voice.quiet.eyebrow': '每日日志 · {date}',
  'voice.quiet.title': '记入今天',
  'voice.quiet.subtitle': '安静记录吃饭、散步、小睡与更多日常。',
  'voice.notebook.eyebrow': '每日笔记 · {date}',
  'voice.notebook.title': '写下这一刻',
  'voice.notebook.subtitle': '现在记一笔，整天都清清楚楚。',
  'voice.playful.eyebrow': '狗狗签到 · {date}',
  'voice.playful.title': '狗狗刚才忙什么啦？',
  'voice.playful.subtitle': '先点一下，故事可以稍后再补。',
  'voice.technical.eyebrow': '活动控制台 · {date}',
  'voice.technical.title': '记录一个事件',
  'voice.technical.subtitle': '先保存时间戳，稍后再补充细节。',
  'voice.outdoors.eyebrow': '户外日志 · {date}',
  'voice.outdoors.title': '标记今天的足迹',
  'voice.outdoors.subtitle': '把停留、散步和休息都留在视野里。',
  'voice.calm.eyebrow': '每日流动 · {date}',
  'voice.calm.title': '记下日常节奏',
  'voice.calm.subtitle': '轻轻一点，让这一天自然延续。',
  'voice.editorial.eyebrow': '今日刊 · {date}',
  'voice.editorial.title': '今日动态',
  'voice.editorial.subtitle': '把最新一刻写进今天的记录。',
  'voice.direct.eyebrow': '快速记录 · {date}',
  'voice.direct.title': '选择一个动作',
  'voice.direct.subtitle': '轻点一次，记录当前时间。',
};

const spanish: Dictionary = {
  'language.system': 'Sistema',
  'language.systemDetail': 'Usar el idioma del dispositivo',
  'language.en': 'Inglés',
  'language.zh-Hans': 'Chino simplificado',
  'language.es': 'Español',
  'nav.log': 'Hoy',
  'nav.timeline': 'Cronología',
  'nav.insights': 'Análisis',
  'nav.schedule': 'Rutina',
  'appearance.title': 'Elige la apariencia',
  'appearance.subtitle': '10 estilos visuales, cada uno con su propia voz e iconos.',
  'appearance.themeHeading': 'TEMA',
  'appearance.languageHeading': 'IDIOMA',
  'appearance.languageHint': 'El idioma se guarda por separado del tema visual.',
  'appearance.close': 'Cerrar selector de apariencia',
  'theme.meadow.detail': 'Diario suave · relajado',
  'theme.sunrise.detail': 'Lista nítida · compacta',
  'theme.midnight.detail': 'Tarjetas flotantes · amplias',
  'theme.paper.detail': 'Cuaderno monocromo · cuadrado',
  'theme.bubblegum.detail': 'Burbujas alegres · grandes',
  'theme.blueprint.detail': 'Plano técnico · denso',
  'theme.trail.detail': 'Tarjetas robustas · firmes',
  'theme.tide.detail': 'Cápsulas ligeras · serenas',
  'theme.plum.detail': 'Bloques editoriales · intensos',
  'theme.contrast.detail': 'Contornos fuertes · máxima claridad',
  'event.pee': 'Pipí',
  'event.poop': 'Caca',
  'event.meal': 'Comida',
  'event.pottyTrip': 'Salida al baño',
  'event.walk': 'Paseo',
  'event.nap': 'Siesta',
  'event.custom': 'Otro',
  'eventPast.pee': 'Hizo pipí',
  'eventPast.poop': 'Hizo caca',
  'eventPast.meal': 'Comió',
  'eventPast.pottyTrip': 'Salió al baño',
  'eventPast.walk': 'Salió de paseo',
  'eventPast.nap': 'Empezó una siesta',
  'eventPast.custom': 'Otra actividad',
  'eventPast.napRunning': 'Siesta en curso',
  'eventPast.napped': 'Durmió la siesta',
  'time.justNow': 'ahora mismo',
  'time.minutes': '{count} min',
  'time.hours': '{count} h',
  'time.days': '{count} d',
  'time.minutesAgo': 'hace {count} min',
  'time.hoursAgo': 'hace {count} h',
  'time.daysAgo': 'hace {count} d',
  'quick.endNap': 'Terminar siesta',
  'quick.endNapA11y': 'Terminar la siesta actual',
  'quick.endNapHint': 'Guarda la hora de fin de la siesta',
  'quick.logAction': 'Registrar {activity}',
  'quick.logHint': 'Añade la hora actual al registro de actividad',
  'quick.running': '{time} en curso',
  'quick.notYet': 'Aún no',
  'quick.another': 'Otra actividad',
  'quick.anotherHint': 'Abre actividades habituales y personalizadas',
  'quick.logAnother': 'Registrar otra actividad',
  'quick.commonChoices': 'Las opciones habituales están a un toque.',
  'quick.customActivity': 'ACTIVIDAD PERSONALIZADA',
  'quick.customPlaceholder': 'p. ej., Cepillado',
  'quick.customName': 'Nombre de la actividad personalizada',
  'quick.customLogA11y': 'Registrar ahora la actividad personalizada',
  'quick.logNow': 'Registrar ahora',
  'quick.close': 'Cerrar selector de actividad',
  'quick.water': 'Agua',
  'quick.accident': 'Accidente',
  'quick.play': 'Juego',
  'quick.training': 'Entrenamiento',
  'quick.crate': 'Jaula',
  'quick.medicine': 'Medicina',
  'routine.eyebrow': 'RITMO DE HOY',
  'routine.build': 'Crea un ritmo diario',
  'routine.buildDetail': 'Añade los horarios que quieras repetir cada día.',
  'routine.due': 'Toca {activity}',
  'routine.at': '{activity} a las {time}',
  'routine.missedOne': '1 momento de la rutina necesita atención',
  'routine.missedMany': '{count} momentos de la rutina necesitan atención',
  'routine.complete': 'La rutina de hoy está completa',
  'routine.plannedFor': 'Programado para las {time}',
  'routine.inMinutes': 'en {count} min',
  'routine.inHours': 'en {count} h',
  'routine.inHoursMinutes': 'en {hours} h {minutes} min',
  'routine.now': 'ahora',
  'routine.progress': '{completed} de {total} completados',
  'routine.logged': '{completed} de {total} actividades previstas registradas',
  'routine.openHint': 'Abre la rutina diaria',
  'common.undo': 'Deshacer',
  'common.addNote': 'Añadir nota',
  'common.addNoteA11y': 'Añadir una nota a este registro',
  'common.done': 'Listo',
  'eventRow.now': 'ahora',
  'eventRow.running': 'en curso',
  'eventRow.widget': 'Widget',
  'eventRow.app': 'App',
  'eventRow.edit': 'Editar registro de {activity}',
  'eventRow.editNapHint': 'Abre los controles de fecha, hora y nota',
  'eventRow.editHint': 'Abre los controles de actividad, fecha, hora y nota',
  'eventRow.delete': 'Eliminar {activity} a las {time}',
  'note.listeningAnnouncement': 'Escuchando la nota',
  'note.transcribeErrorTitle': 'No se pudo transcribir',
  'note.accessOff': 'El acceso al micrófono o al reconocimiento de voz está desactivado. Puedes activarlo en Ajustes o escribir la nota.',
  'note.tryAgain': 'Prueba de nuevo el micrófono o escribe la nota.',
  'note.unavailableTitle': 'Notas de voz no disponibles',
  'note.unavailableBody': 'El reconocimiento de voz no está disponible en este teléfono. Aún puedes escribir la nota.',
  'note.permissionTitle': 'Se necesita acceso al micrófono',
  'note.permissionBody': 'Permite el acceso al micrófono y al reconocimiento de voz para dictar notas. Aún puedes escribir la nota.',
  'note.startError': 'No se pudo iniciar el reconocimiento de voz. Aún puedes escribir la nota.',
  'note.label': 'Nota de este registro',
  'note.placeholder': 'p. ej., Justo después de jugar',
  'note.stopDictating': 'Detener el dictado de la nota',
  'note.dictate': 'Dictar nota',
  'note.listeningHint': 'Escuchando… Toca detener cuando termines.',
  'note.idleHint': 'Escribe una nota o toca el micrófono para dictarla.',
  'log.customizeWidgetA11y': 'Personalizar el widget de inicio',
  'log.changeAppearanceA11y': 'Cambiar apariencia e idioma',
  'log.activity': 'Actividad',
  'log.totalCount': '{count} en total',
  'log.recentCount': '{count} recientes',
  'log.filter.all': 'Todo',
  'log.filter.potty': 'Baño',
  'log.filter.meals': 'Comidas',
  'log.filter.walks': 'Paseos',
  'log.filter.naps': 'Siestas',
  'log.filter.other': 'Otro',
  'log.showFilter': 'Mostrar actividad de {filter}',
  'log.showRecentA11y': 'Mostrar actividad de los últimos {count} días',
  'log.viewAllA11y': 'Ver todo el historial, incluidos {count} registros anteriores',
  'log.showRecent': 'Mostrar los últimos {count} días',
  'log.viewAll': 'Ver todo el historial',
  'log.recentDetail': 'Volver a la actividad más relevante ahora',
  'log.olderDetail': '{count} registros anteriores agrupados por mes',
  'log.today': 'Hoy',
  'log.yesterday': 'Ayer',
  'log.emptyTitle': 'Tu registro empieza aquí',
  'log.emptyFilteredTitle': 'No hay registros de {filter}',
  'log.emptyBody': 'Toca una acción de arriba cuando ocurra.',
  'log.emptyFilteredBody': 'Elige otro filtro o registra una actividad arriba.',
  'log.saveErrorTitle': 'No se pudieron guardar los cambios',
  'log.saveErrorBody': 'Mantén abierto el editor y toca el estado de guardado para intentarlo de nuevo.',
  'log.widgetErrorTitle': 'No se pudo guardar la configuración del widget',
  'log.tryAgain': 'Inténtalo de nuevo.',
  'editor.editNap': 'Editar siesta',
  'editor.editLog': 'Editar registro',
  'editor.napSubtitle': '{activity} · Corrige la hora o la nota.',
  'editor.logSubtitle': '{activity} · Corrige la actividad, la hora o la nota.',
  'editor.close': 'Cerrar editor del registro',
  'editor.retryA11y': 'No se pudieron guardar los cambios. Reintentar ahora',
  'editor.retry': 'No se pudo guardar. Toca para reintentar.',
  'editor.customNameStatus': 'Añade un nombre personalizado para guardar esta actividad.',
  'editor.saving': 'Guardando cambios…',
  'editor.saved': 'Guardado automáticamente',
  'editor.autoSave': 'Los cambios se guardan automáticamente',
  'editor.activity': 'ACTIVIDAD',
  'editor.changeActivity': 'Cambiar actividad a {activity}',
  'editor.customName': 'NOMBRE PERSONALIZADO',
  'editor.customNameA11y': 'Nombre de actividad personalizada',
  'editor.customNameHint': 'Obligatorio. Los cambios se guardan automáticamente al escribir.',
  'editor.customPlaceholder': 'p. ej., Cepillado',
  'editor.customInvalid': 'Introduce un nombre para la actividad.',
  'editor.customValid': 'Usa un nombre corto que reconozcas en el registro.',
  'editor.now': 'ahora',
  'editor.inProgress': 'en curso',
  'editor.start': 'INICIO',
  'editor.end': 'FIN',
  'editor.date': 'fecha',
  'editor.time': 'hora',
  'editor.editNapTime': 'Editar hora de {field} de la siesta',
  'editor.quickBackdate': 'REGISTRO RETROACTIVO',
  'editor.setField': 'FIJAR {field}',
  'editor.backdate': 'Fijar la hora hace {count} minutos',
  'editor.setNow': 'Fijar la hora actual',
  'editor.minutesAgo': 'hace {count} min',
  'editor.dateTime': 'FECHA Y HORA',
  'editor.chooseDate': 'Elegir fecha de {field}, actualmente {date}',
  'editor.chooseTime': 'Elegir hora exacta de {field}, actualmente {time}',
  'editor.finishPicker': 'Terminar de elegir {picker}',
  'editor.note': 'NOTA',
  'widget.title': 'Personalizar widget',
  'widget.subtitle': 'Elige entre 2 y 4 acciones. Los widgets pequeños las muestran en una fila.',
  'widget.close': 'Cerrar configuración del widget',
  'widget.actions': 'ACCIONES DEL WIDGET · {count} DE 4',
  'widget.addAction': 'Añadir {activity} al widget',
  'widget.removeAction': 'Quitar {activity} del widget',
  'widget.keepTwo': 'Mantén al menos dos acciones en el widget.',
  'widget.removeFirst': 'Quita primero otra acción.',
  'widget.napHint': 'La siesta sigue disponible mientras está en curso, aunque la ocultes del conjunto predeterminado.',
  'widget.save': 'Guardar configuración del widget',
  'common.saving': 'Guardando…',
  'app.napEnded': 'Siesta terminada',
  'app.napStarted': 'Siesta iniciada',
  'app.logged': '{activity} registrado',
  'app.estimateAdded': '{activity} añadido a la hora estimada',
  'app.deleteTitle': '¿Eliminar este registro?',
  'app.deleteMessage': '{activity} a las {time}',
  'app.cancel': 'Cancelar',
  'app.delete': 'Eliminar',
  'app.routineSaved': 'Rutina guardada',
  'app.notificationsOff': 'Las notificaciones están desactivadas, por lo que no se pudieron programar recordatorios.',
  'app.reminderError': 'Puptime no pudo actualizar los recordatorios. Intenta editar la rutina de nuevo.',
  'schedule.eyebrow': 'RUTINA DIARIA',
  'schedule.title': 'Haz que el día sea predecible',
  'schedule.subtitle': 'Empieza con los patrones de tus registros o edita las horas. Es planificación de rutina, no consejo veterinario.',
  'schedule.status.logged': 'Registrado',
  'schedule.status.due': 'Toca ahora',
  'schedule.status.missed': 'Perdido',
  'schedule.status.upcoming': 'Próximo',
  'schedule.saveErrorTitle': 'No se pudo guardar la rutina',
  'schedule.saveErrorBody': 'Tu rutina anterior sigue disponible. Inténtalo de nuevo.',
  'schedule.notificationsOff': 'Las notificaciones están desactivadas',
  'schedule.notificationsBody': 'Permite las notificaciones de Puptime en los ajustes del sistema para usar recordatorios diarios.',
  'schedule.notNow': 'Ahora no',
  'schedule.openSettings': 'Abrir ajustes',
  'schedule.reminderErrorTitle': 'No se pudieron activar los recordatorios',
  'schedule.reminderErrorBody': 'Inténtalo de nuevo desde esta entrada de la rutina.',
  'schedule.removeTitle': '¿Quitar esta hora?',
  'schedule.entryAt': '{activity} a las {time}',
  'schedule.remove': 'Quitar',
  'schedule.removeErrorTitle': 'No se pudo quitar la hora',
  'schedule.removeErrorBody': 'Tu rutina no ha cambiado. Inténtalo de nuevo.',
  'schedule.suggestionErrorTitle': 'No se pudo usar la rutina sugerida',
  'schedule.suggestionErrorBody': 'Tu rutina actual sigue disponible. Inténtalo de nuevo.',
  'schedule.learnTitle': 'Crear desde tus registros',
  'schedule.learnBody': 'Busca actividades que se repiten la mayoría de los días registrados y redondea sus horas habituales a 15 minutos.',
  'schedule.suggestedTimes': '{count} horas sugeridas a partir de {days} días registrados',
  'schedule.needDays': 'Registra actividad durante {count} días más para encontrar una rutina',
  'schedule.noPattern': 'Todavía no hay un patrón diario claro; sigue registrando',
  'schedule.previewA11y': 'Previsualizar {count} horas sugeridas para la rutina',
  'schedule.notEnoughA11y': 'No hay suficientes registros repetidos para sugerir una rutina',
  'schedule.previewButton': 'Previsualizar rutina sugerida',
  'schedule.keepLogging': 'Sigue registrando para desbloquear',
  'schedule.todaySoFar': 'HOY HASTA AHORA',
  'schedule.loggedProgress': '{completed} de {total} registrados',
  'schedule.dueOne': 'Hay 1 actividad pendiente ahora',
  'schedule.dueMany': 'Hay {count} actividades pendientes ahora',
  'schedule.missedOne': '1 momento perdido',
  'schedule.missedMany': '{count} momentos perdidos',
  'schedule.everythingLogged': 'Todo lo previsto está registrado',
  'schedule.nextAhead': 'La próxima actividad aún está por llegar',
  'schedule.windowHint': 'Un registro cuenta como puntual si está dentro de los 30 minutos de la hora prevista.',
  'schedule.todayPlan': 'Plan de hoy',
  'schedule.timeCount': '{count} horas',
  'schedule.emptyTitle': 'No hay horas previstas',
  'schedule.emptyBody': 'Añade los momentos que quieras repetir cada día.',
  'schedule.editA11y': 'Editar {activity} a las {time}, {status}{reminder}',
  'schedule.reminderOn': ', recordatorio diario activado',
  'schedule.removeA11y': 'Quitar {activity} a las {time}',
  'schedule.addA11y': 'Añadir una hora a la rutina',
  'schedule.addTime': 'Añadir una hora',
  'schedule.suggestionTitle': 'Rutina a partir de tus registros',
  'schedule.suggestionSubtitle': 'Basada en {days} días registrados de los últimos {period}. Revisa cada hora antes de usarla.',
  'schedule.closeSuggestion': 'Cerrar rutina sugerida',
  'schedule.replaceCurrent': 'Al usarla, sustituirás tus {count} horas actuales. ',
  'schedule.createRoutine': 'Al usarla, crearás tu rutina. ',
  'schedule.remindersStayOff': 'Los recordatorios siguen desactivados hasta que los actives en cada hora.',
  'schedule.usingRoutine': 'Aplicando rutina…',
  'schedule.useRoutine': 'Usar esta rutina',
  'schedule.keepRoutine': 'Mantener rutina actual',
  'schedule.editTime': 'Editar hora',
  'schedule.close': 'Cerrar',
  'schedule.activity': 'ACTIVIDAD',
  'schedule.time': 'HORA',
  'schedule.change': 'Cambiar',
  'schedule.reminder': 'RECORDATORIO',
  'schedule.dailyReminder': 'Recordatorio diario',
  'schedule.reminderHint': 'Avisa a esta hora prevista en este dispositivo.',
  'schedule.reminderA11y': 'Recordatorio diario para esta entrada de la rutina',
  'schedule.saveTime': 'Guardar hora',
  'insights.activity': 'actividad',
  'insights.selectedActivity': 'actividad seleccionada',
  'insights.noSelected': 'No hay actividades seleccionadas',
  'insights.allActivity': 'Toda la actividad',
  'insights.timing': 'Horario de {activities}',
  'insights.activityCount': '{count} actividades',
  'insights.pointWindow': '{activity} en la franja de {start} a {end}',
  'insights.durationWindow': '{activity} de aproximadamente {start} a {end}',
  'insights.perDay': '{value}/día',
  'insights.eachRecordedDay': '{count} en cada día registrado',
  'insights.rangePerDay': '{minimum}–{maximum} por día registrado',
  'insights.noLogsYet': 'Aún no hay registros de {activity}',
  'insights.needAnotherLog': 'Hace falta otro registro',
  'insights.middleHalf': 'Mitad central: {lower}–{upper}',
  'insights.gapsObserved': '{count} intervalos observados',
  'insights.logCount': '{count} registros',
  'insights.averageFrequency': 'FRECUENCIA MEDIA',
  'insights.typicalGap': 'INTERVALO TÍPICO',
  'insights.noLogged': 'No hay registros de {activity}',
  'insights.noActivitySelected': 'No hay actividad seleccionada',
  'insights.today': 'HOY',
  'insights.currentTime': 'Hora actual: {time}',
  'insights.decrease': 'Reducir {control}',
  'insights.increase': 'Aumentar {control}',
  'insights.thisMonth': 'Este mes',
  'insights.monthA11y': '{month}. {average} registros de {activity} por día registrado. {logs} registros en {days} días registrados.',
  'insights.monthDetail': '{logs} registros · {days} días con actividad',
  'insights.exportErrorTitle': 'No se pudo exportar la actividad',
  'insights.exportErrorBody': 'Inténtalo de nuevo. Tus datos de Puptime no han cambiado.',
  'insights.estimateErrorTitle': 'No se pudo añadir esta estimación',
  'insights.estimateErrorBody': 'Tu historial de actividad no ha cambiado. Inténtalo de nuevo.',
  'insights.eyebrow': 'PATRONES DE TUS REGISTROS',
  'insights.title': 'Una rutina más clara',
  'insights.subtitle': 'Frecuencia, posibles ausencias y contexto a largo plazo a partir de tus registros.',
  'insights.frequencyTitle': 'Frecuencia de tus registros',
  'insights.frequencyCaption': 'Últimos {period} días · {recorded} días con actividad · observaciones, no objetivos',
  'insights.frequencyNote': 'Los promedios diarios incluyen ceros en los días en que registraste otra actividad. Los días completamente vacíos se excluyen porque pueden no haberse registrado.',
  'insights.gapsTitle': 'Posibles ausencias',
  'insights.gapsCaption': 'Horas repetidas de {count} días activos',
  'insights.gapsNote': 'Solo aparece una sugerencia cuando la misma actividad se registró cerca de esa hora en al menos 3 días más y hubo registros después. No se añade nada automáticamente.',
  'insights.mealName': 'Comida',
  'insights.around': 'sobre las {time}',
  'insights.aboutRange': 'aprox. {start}–{end}',
  'insights.possibleNap': 'Posible siesta no registrada',
  'insights.mayBeUnlogged': 'Puede faltar {activity}',
  'insights.seenEvidence': 'Visto cerca de esta hora en {observed} de {compared} días activos adicionales.',
  'insights.addEstimateA11y': 'Añadir {activity} a la hora estimada',
  'insights.adding': 'Añadiendo…',
  'insights.addLog': 'Añadir registro',
  'insights.needGapDays': 'Registra actividad durante {count} días más para buscar ausencias.',
  'insights.noGaps': 'No se encontraron ausencias claras en los últimos {count} días.',
  'insights.timelineActivities': 'Actividades de la cronología',
  'insights.selectCombination': 'Elige cualquier combinación',
  'insights.all': 'Todo',
  'insights.clearFilters': 'Borrar todos los filtros de actividad',
  'insights.selectFilters': 'Seleccionar todos los filtros de actividad',
  'insights.hideTiming': 'Ocultar horario de {activity}',
  'insights.showTiming': 'Mostrar horario de {activity}',
  'insights.panelCaption': '{range} · {count} registros · más antiguos arriba',
  'insights.timeWidth': 'Ancho temporal',
  'insights.dayHeight': 'Días visibles',
  'insights.zoomHint': 'Muestra más días para alejar la vista vertical. Amplía el ancho temporal y desliza el gráfico para revisar los periodos con más actividad.',
  'insights.showEarlier': 'Mostrar fechas anteriores',
  'insights.earlier': 'Anteriores',
  'insights.latestDays': 'Últimos {count} días',
  'insights.olderWindow': 'Periodo anterior de {count} días',
  'insights.showNewer': 'Mostrar fechas más recientes',
  'insights.newer': 'Recientes',
  'insights.chooseActivity': 'Elige al menos una actividad arriba para mostrarla en la cronología.',
  'insights.noRangeLogs': 'No hay registros de {activity} en este intervalo.',
  'insights.historyTitle': 'Contexto mes a mes',
  'insights.historyCaption': 'Toda la actividad · mes más reciente primero',
  'insights.historyNote': 'El ritmo mensual usa los días en los que registraste alguna actividad, por lo que los meses incompletos o sin registrar no se tratan como ceros.',
  'insights.showRecentMonths': 'Mostrar meses recientes',
  'insights.showAllMonths': 'Mostrar los {count} meses',
  'insights.dataTitle': 'Tus datos',
  'insights.dataBody': 'Comparte todos los registros como CSV listo para una hoja de cálculo. Nada sale de este dispositivo hasta que eliges dónde enviarlo.',
  'insights.exportA11y': 'Exportar toda la actividad como CSV',
  'insights.noExport': 'No hay actividad para exportar',
  'insights.exportHint': 'Abre la hoja para compartir del sistema',
  'insights.preparingExport': 'Preparando exportación…',
  'insights.exportButton': 'Exportar actividad CSV',
  'timeline.eyebrow': 'RITMO DIARIO · FRANJAS DE 15 MINUTOS',
  'timeline.title': 'Cuándo ocurren las cosas',
  'timeline.subtitle': 'Desplázate hacia arriba para ver días anteriores. Pellizca o usa los botones para ampliar el tiempo.',
  'timeline.date': 'FECHA',
  'timeline.zoomOut': 'Reducir la escala temporal',
  'timeline.zoomIn': 'Ampliar la escala temporal',
  'timeline.range': '{range} · {count} registros',
  'timeline.pinchHint': 'Pellizca para ampliar el tiempo',
  'timeline.loadEarlier': 'Cargar días anteriores',
  'timeline.loadingEarlier': 'Cargando días anteriores',
  'timeline.historyStart': 'No hay días registrados anteriores',
  'voice.gentle.eyebrow': 'PUPTIME · {date}',
  'voice.gentle.title': '¿Qué acaba de pasar?',
  'voice.gentle.subtitle': 'Un toque mantiene cerca el día de tu cachorro.',
  'voice.brisk.eyebrow': 'REGISTRO RÁPIDO · {date}',
  'voice.brisk.title': 'Regístralo mientras está fresco',
  'voice.brisk.subtitle': 'Toques rápidos ahora, una cronología clara después.',
  'voice.quiet.eyebrow': 'REGISTRO DIARIO · {date}',
  'voice.quiet.title': 'Añádelo a hoy',
  'voice.quiet.subtitle': 'Un registro tranquilo de comidas, paseos, siestas y más.',
  'voice.notebook.eyebrow': 'NOTAS DIARIAS · {date}',
  'voice.notebook.title': 'Anota el momento',
  'voice.notebook.subtitle': 'Una línea ahora mantiene todo el día legible.',
  'voice.playful.eyebrow': 'REVISIÓN DEL CACHORRO · {date}',
  'voice.playful.title': '¿Qué ha hecho tu cachorro?',
  'voice.playful.subtitle': 'Tócalo ahora; puedes contar la historia después.',
  'voice.technical.eyebrow': 'CONSOLA DE ACTIVIDAD · {date}',
  'voice.technical.title': 'Registra un evento',
  'voice.technical.subtitle': 'Guarda la hora ahora y completa los detalles después.',
  'voice.outdoors.eyebrow': 'DIARIO DE CAMPO · {date}',
  'voice.outdoors.title': 'Marca el recorrido',
  'voice.outdoors.subtitle': 'Mantén a la vista las paradas, paseos y descansos de hoy.',
  'voice.calm.eyebrow': 'FLUJO DIARIO · {date}',
  'voice.calm.title': 'Captura el ritmo',
  'voice.calm.subtitle': 'Un toque suave mantiene el día en marcha.',
  'voice.editorial.eyebrow': 'LA EDICIÓN DIARIA · {date}',
  'voice.editorial.title': 'Hoy, en movimiento',
  'voice.editorial.subtitle': 'Añade el último momento al registro.',
  'voice.direct.eyebrow': 'REGISTRO RÁPIDO · {date}',
  'voice.direct.title': 'Elige una acción',
  'voice.direct.subtitle': 'Un toque registra la hora actual.',
};

const dictionaries: Record<AppLanguage, Dictionary> = {
  en: english,
  'zh-Hans': simplifiedChinese,
  es: spanish,
};

export type TranslationVariables = Record<string, string | number>;

export function isLanguagePreference(value: string | null): value is LanguagePreference {
  return value !== null && languageChoices.includes(value as LanguagePreference);
}

export function resolveLanguage(
  preference: LanguagePreference,
  deviceLocale = Intl.DateTimeFormat().resolvedOptions().locale,
): AppLanguage {
  if (preference !== 'system') return preference;
  const locale = deviceLocale.toLowerCase();
  if (locale.startsWith('zh')) return 'zh-Hans';
  if (locale.startsWith('es')) return 'es';
  return 'en';
}

export function translate(
  language: AppLanguage,
  key: MessageKey,
  variables: TranslationVariables = {},
): string {
  return dictionaries[language][key].replace(/\{(\w+)\}/g, (match, name: string) => (
    Object.prototype.hasOwnProperty.call(variables, name) ? String(variables[name]) : match
  ));
}

const eventKeys: Record<EventType, MessageKey> = {
  pee: 'event.pee',
  poop: 'event.poop',
  meal: 'event.meal',
  pottyTrip: 'event.pottyTrip',
  walk: 'event.walk',
  nap: 'event.nap',
  custom: 'event.custom',
};

const eventPastKeys: Record<EventType, MessageKey> = {
  pee: 'eventPast.pee',
  poop: 'eventPast.poop',
  meal: 'eventPast.meal',
  pottyTrip: 'eventPast.pottyTrip',
  walk: 'eventPast.walk',
  nap: 'eventPast.nap',
  custom: 'eventPast.custom',
};

export function localizedEventLabel(language: AppLanguage, type: EventType): string {
  return translate(language, eventKeys[type]);
}

export function localizedEventPastLabel(language: AppLanguage, event: PuppyEvent): string {
  if (event.type === 'custom' && event.customLabel?.trim()) return event.customLabel.trim();
  if (event.type === 'nap' && event.endedAt === null) return translate(language, 'eventPast.napRunning');
  if (event.type === 'nap' && typeof event.endedAt === 'number') return translate(language, 'eventPast.napped');
  return translate(language, eventPastKeys[event.type]);
}

export function localizedRelativeTime(language: AppLanguage, value: number, now = Date.now()): string {
  const minutes = Math.max(0, Math.floor((now - value) / 60_000));
  if (minutes < 1) return translate(language, 'time.justNow');
  if (minutes < 60) return translate(language, 'time.minutesAgo', { count: minutes });
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return translate(language, 'time.hoursAgo', { count: hours });
  return translate(language, 'time.daysAgo', { count: Math.floor(hours / 24) });
}

export function localizedElapsedTime(language: AppLanguage, value: number, now = Date.now()): string {
  const minutes = Math.max(0, Math.floor((now - value) / 60_000));
  if (minutes < 60) return translate(language, 'time.minutes', { count: minutes });
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return translate(language, 'time.hours', { count: hours });
  return translate(language, 'time.days', { count: Math.floor(hours / 24) });
}

const voiceKeys: Record<ThemeVoice, { eyebrow: MessageKey; title: MessageKey; subtitle: MessageKey }> = {
  gentle: { eyebrow: 'voice.gentle.eyebrow', title: 'voice.gentle.title', subtitle: 'voice.gentle.subtitle' },
  brisk: { eyebrow: 'voice.brisk.eyebrow', title: 'voice.brisk.title', subtitle: 'voice.brisk.subtitle' },
  quiet: { eyebrow: 'voice.quiet.eyebrow', title: 'voice.quiet.title', subtitle: 'voice.quiet.subtitle' },
  notebook: { eyebrow: 'voice.notebook.eyebrow', title: 'voice.notebook.title', subtitle: 'voice.notebook.subtitle' },
  playful: { eyebrow: 'voice.playful.eyebrow', title: 'voice.playful.title', subtitle: 'voice.playful.subtitle' },
  technical: { eyebrow: 'voice.technical.eyebrow', title: 'voice.technical.title', subtitle: 'voice.technical.subtitle' },
  outdoors: { eyebrow: 'voice.outdoors.eyebrow', title: 'voice.outdoors.title', subtitle: 'voice.outdoors.subtitle' },
  calm: { eyebrow: 'voice.calm.eyebrow', title: 'voice.calm.title', subtitle: 'voice.calm.subtitle' },
  editorial: { eyebrow: 'voice.editorial.eyebrow', title: 'voice.editorial.title', subtitle: 'voice.editorial.subtitle' },
  direct: { eyebrow: 'voice.direct.eyebrow', title: 'voice.direct.title', subtitle: 'voice.direct.subtitle' },
};

export function themeVoiceCopy(language: AppLanguage, voice: ThemeVoice, date: string) {
  const keys = voiceKeys[voice];
  return {
    eyebrow: translate(language, keys.eyebrow, { date }),
    title: translate(language, keys.title),
    subtitle: translate(language, keys.subtitle),
  };
}
