import type { EventType, PuppyEvent } from './domain';

export type AppLanguage = 'en' | 'zh-Hans' | 'es';
export type LanguagePreference = 'system' | AppLanguage;

export const languageChoices: readonly LanguagePreference[] = ['system', 'en', 'zh-Hans', 'es'];

const english = {
  'language.system': 'System',
  'language.systemDetail': 'Follow this device',
  'language.en': 'English',
  'language.zh-Hans': 'Simplified Chinese',
  'language.es': 'Spanish',
  'nav.log': 'Today',
  'nav.timeline': 'Timeline',
  'nav.insights': 'Insights',
  'nav.schedule': 'Schedule',
  'settings.title': 'Settings',
  'settings.back': 'Back to Today',
  'settings.personalization': 'PERSONALIZATION',
  'settings.theme': 'Theme',
  'settings.themeDetail': 'Colors and layout',
  'settings.language': 'Language',
  'settings.widget': 'WIDGET',
  'settings.widgetDetail': 'Choose 2–4 actions.',
  'settings.notifications': 'NOTIFICATIONS',
  'settings.notificationPermission': 'Notification access',
  'settings.permissionGranted': 'Allowed',
  'settings.permissionRequestable': 'Needed for reminders and confirmations',
  'settings.permissionBlocked': 'Off in device settings',
  'settings.allowNotifications': 'Allow notifications',
  'settings.routineReminders': 'Routine reminders',
  'settings.routineRemindersDetail': '{count} enabled',
  'settings.manageSchedule': 'Manage schedule',
  'settings.reminderTiming': 'Reminder timing',
  'settings.reminderTimingDetail': 'Used for all routine reminders.',
  'settings.atTime': 'At time',
  'settings.minutesBefore': '{count} min before',
  'settings.pottyNudges': 'Potty nudges',
  'settings.pottyNudgesDetail': 'Based on the latest log. Logging a pee resets the timers.',
  'settings.afterPeeReminder': 'After a pee',
  'settings.afterPeeReminderDetail': 'Remind when it may be time to go again.',
  'settings.afterMealReminder': 'After a meal',
  'settings.afterMealReminderDetail': 'Remind about a possible post-meal potty break.',
  'settings.widgetConfirmations': 'Widget confirmations',
  'settings.widgetConfirmationsDetail': 'Show a notification after each widget log.',
  'settings.saveErrorTitle': 'Couldn’t save settings',
  'settings.saveErrorBody': 'The previous settings were kept. Try again.',
  'settings.themePickerTitle': 'Choose a theme',
  'settings.languagePickerTitle': 'Choose a language',
  'settings.closePicker': 'Close settings picker',
  'settings.guide': 'App guide',
  'settings.guideDetail': 'See logging, routines, and reminders',
  'onboarding.skip': 'Skip',
  'onboarding.progress': 'Step {step} of 4',
  'onboarding.logTitle': 'Log the little things.',
  'onboarding.logBody': 'One tap for potty, meals, walks, and naps.',
  'onboarding.preview': 'EXAMPLE',
  'onboarding.todayPreview': 'Today',
  'onboarding.mealPreview': 'Meal',
  'onboarding.peePreview': 'Pee',
  'onboarding.walkPreview': 'Walk',
  'onboarding.timelineTitle': 'See the pattern.',
  'onboarding.timelineBody': 'See when things happened each day. Zoom in for detail.',
  'onboarding.timelineYesterday': 'Yesterday',
  'onboarding.timelineEarlier': 'Earlier',
  'onboarding.routineTitle': 'Plan your day.',
  'onboarding.routineBody': 'Add times to Schedule. Set reminders when you need them.',
  'onboarding.routinePreview': 'Daily routine',
  'onboarding.nudgeTitle': 'Get helpful nudges.',
  'onboarding.nudgeBody': 'Potty nudges and reminders for your routine.',
  'onboarding.notificationExampleTitle': 'Potty break?',
  'onboarding.notificationExampleBody': '30 minutes after a meal.',
  'onboarding.routineDetail': 'Before planned activities',
  'onboarding.widgetDetail': 'Optional, for home-screen logs',
  'onboarding.changeLater': 'Change alerts anytime in Settings.',
  'onboarding.continue': 'Next',
  'onboarding.start': 'Start logging',
  'onboarding.allow': 'Allow notifications',
  'onboarding.later': 'Not now',
  'onboarding.back': 'Back',
  'notifications.reminderSoon': '{activity} in {minutes} min',
  'notifications.reminderNow': 'Time for {activity}',
  'notifications.reminderBody': 'Scheduled for {time}. Tap to log it.',
  'notifications.delayMinutes': '{count} minutes',
  'notifications.delayOneHour': '1 hour',
  'notifications.delayHours': '{count} hours',
  'notifications.afterPeeTitle': 'Potty break?',
  'notifications.afterPeeBody': 'It’s been {delay} since the last pee. Your puppy may need to go again.',
  'notifications.afterMealTitle': 'Potty break after eating?',
  'notifications.afterMealBody': 'It’s been {delay} since the last meal. Your puppy may need to go.',
  'notifications.widgetLoggedTitle': 'Activity logged',
  'notifications.widgetLoggedBody': '{activity} saved from the widget.',
  'notifications.addNote': 'Add note',
  'notifications.editDetails': 'Edit details',
  'notifications.saveNote': 'Save',
  'notifications.notePlaceholder': 'Add a note',
  'theme.meadow.detail': 'Soft colors · rounded',
  'theme.sunrise.detail': 'Warm colors · compact',
  'theme.midnight.detail': 'Dark colors · roomy',
  'theme.paper.detail': 'Black and white · square',
  'theme.bubblegum.detail': 'Pink · rounded',
  'theme.blueprint.detail': 'Blue grid · compact',
  'theme.trail.detail': 'Earth tones · angular',
  'theme.tide.detail': 'Blue-green · rounded',
  'theme.plum.detail': 'Purple · angular',
  'theme.contrast.detail': 'Black and white · high contrast',
  'event.pee': 'Pee',
  'event.poop': 'Poop',
  'event.meal': 'Ate',
  'event.pottyTrip': 'Potty trip',
  'event.walk': 'Walk',
  'event.nap': 'Nap',
  'event.custom': 'Other',
  'eventPast.pee': 'Peed',
  'eventPast.poop': 'Pooped',
  'eventPast.meal': 'Ate a meal',
  'eventPast.pottyTrip': 'Went out for potty',
  'eventPast.walk': 'Went for a walk',
  'eventPast.nap': 'Started a nap',
  'eventPast.custom': 'Other activity',
  'eventPast.napRunning': 'Nap in progress',
  'eventPast.napped': 'Napped',
  'time.justNow': 'just now',
  'time.minutes': '{count}m',
  'time.hours': '{count}h',
  'time.days': '{count}d',
  'time.minutesAgo': '{count}m ago',
  'time.hoursAgo': '{count}h ago',
  'time.daysAgo': '{count}d ago',
  'quick.endNap': 'End nap',
  'quick.endNapA11y': 'End the current nap',
  'quick.endNapHint': 'Saves the nap end time',
  'quick.logAction': 'Log {activity}',
  'quick.logHint': 'Adds the current time to the activity log',
  'quick.running': '{time} running',
  'quick.another': 'Another activity',
  'quick.anotherHint': 'Opens common and custom activities',
  'quick.logAnother': 'Log another activity',
  'quick.customActivity': 'CUSTOM ACTIVITY',
  'quick.customPlaceholder': 'e.g. Grooming',
  'quick.customName': 'Custom activity name',
  'quick.customLogA11y': 'Log custom activity now',
  'quick.logNow': 'Log now',
  'quick.close': 'Close activity picker',
  'quick.water': 'Water',
  'quick.accident': 'Accident',
  'quick.play': 'Play',
  'quick.training': 'Training',
  'quick.crate': 'Crate',
  'quick.medicine': 'Medicine',
  'routine.build': 'Add a routine',
  'routine.buildDetail': 'Add times and optional reminders.',
  'routine.due': '{activity} due now',
  'routine.at': '{activity} at {time}',
  'routine.missedOne': '1 missed routine time',
  'routine.missedMany': '{count} missed routine times',
  'routine.complete': 'Routine complete',
  'routine.plannedFor': 'Planned for {time}',
  'routine.inMinutes': 'in {count}m',
  'routine.inHours': 'in {count}h',
  'routine.inHoursMinutes': 'in {hours}h {minutes}m',
  'routine.now': 'now',
  'routine.progress': '{completed} of {total} done',
  'routine.logged': '{completed} of {total} planned activities logged',
  'routine.openHint': 'Opens the daily schedule',
  'common.undo': 'Undo',
  'common.addNote': 'Add note',
  'common.addNoteA11y': 'Add a note to this log',
  'common.done': 'Done',
  'eventRow.now': 'now',
  'eventRow.running': 'running',
  'eventRow.widget': 'Widget',
  'eventRow.app': 'App',
  'eventRow.edit': 'Edit {activity} log',
  'eventRow.editNapHint': 'Opens date, time, and note controls',
  'eventRow.editHint': 'Opens activity, date, time, and note controls',
  'eventRow.delete': 'Delete {activity} at {time}',
  'note.listeningAnnouncement': 'Listening for note',
  'note.transcribeErrorTitle': 'Couldn’t transcribe that',
  'note.accessOff': 'Microphone or speech access is off. You can enable it in Settings, or type the note instead.',
  'note.tryAgain': 'Try the microphone again, or type the note instead.',
  'note.unavailableTitle': 'Voice notes unavailable',
  'note.unavailableBody': 'Speech recognition is not available on this phone. You can still type the note.',
  'note.permissionTitle': 'Microphone access needed',
  'note.permissionBody': 'Allow microphone and speech access to dictate notes. You can still type the note.',
  'note.startError': 'The speech recognizer could not start. You can still type the note.',
  'note.label': 'Note for this log',
  'note.placeholder': 'e.g. Just after a play session',
  'note.stopDictating': 'Stop dictating note',
  'note.dictate': 'Dictate note',
  'note.listeningHint': 'Listening… Tap stop when you’re done.',
  'log.customizeWidgetA11y': 'Customize home-screen widget',
  'log.changeAppearanceA11y': 'Change appearance and language',
  'log.openSettingsA11y': 'Open settings',
  'log.activity': 'History',
  'log.filter.all': 'All',
  'log.filter.potty': 'Potty',
  'log.filter.meals': 'Meals',
  'log.filter.walks': 'Walks',
  'log.filter.naps': 'Naps',
  'log.filter.other': 'Other',
  'log.showFilter': 'Show {filter} activity',
  'log.showRecentA11y': 'Show activity from the last {count} days',
  'log.viewAllA11y': 'View all activity history, including {count} older logs',
  'log.showRecent': 'Show recent {count} days',
  'log.viewAll': 'View {count} older logs',
  'log.toggleDayA11y': '{day}, activity count {count}',
  'log.today': 'Today',
  'log.yesterday': 'Yesterday',
  'log.emptyTitle': 'No activity yet',
  'log.emptyRecentTitle': 'No recent activity in the last {count} days',
  'log.emptyFilteredTitle': 'No {filter} logged',
  'log.saveErrorTitle': 'Couldn’t save changes',
  'log.saveErrorBody': 'Tap the save message to try again.',
  'log.widgetErrorTitle': 'Couldn’t save widget settings',
  'log.tryAgain': 'Try again.',
  'editor.editNap': 'Edit nap',
  'editor.editLog': 'Edit log',
  'editor.close': 'Close log editor',
  'editor.retryA11y': 'Couldn’t save changes. Retry now',
  'editor.retry': 'Couldn’t save. Tap to retry.',
  'editor.customNameStatus': 'Add a custom name to save this activity.',
  'editor.saving': 'Saving changes…',
  'editor.activity': 'ACTIVITY',
  'editor.changeActivity': 'Change activity to {activity}',
  'editor.customName': 'CUSTOM NAME',
  'editor.customNameA11y': 'Custom activity name',
  'editor.customNameHint': 'Required. Changes save automatically after you type.',
  'editor.customPlaceholder': 'e.g. Grooming',
  'editor.customInvalid': 'Enter an activity name.',
  'editor.now': 'now',
  'editor.inProgress': 'in progress',
  'editor.start': 'START',
  'editor.end': 'END',
  'editor.date': 'date',
  'editor.time': 'time',
  'editor.editNapTime': 'Edit nap {field} time',
  'editor.quickBackdate': 'QUICK BACKDATE',
  'editor.setField': 'SET {field}',
  'editor.backdate': 'Set time to {count} minutes ago',
  'editor.setNow': 'Set time to now',
  'editor.minutesAgo': '{count}m ago',
  'editor.dateTime': 'DATE & TIME',
  'editor.chooseDate': 'Choose {field} date, currently {date}',
  'editor.chooseTime': 'Choose exact {field} time, currently {time}',
  'editor.finishPicker': 'Finish choosing {picker}',
  'editor.note': 'NOTE',
  'widget.title': 'Customize widget',
  'widget.subtitle': 'Choose 2–4 actions.',
  'widget.close': 'Close widget settings',
  'widget.addAction': 'Add {activity} to the widget',
  'widget.removeAction': 'Remove {activity} from the widget',
  'widget.keepTwo': 'Keep at least two widget actions.',
  'widget.removeFirst': 'Remove another action first.',
  'widget.napHint': 'Nap appears while a nap is running.',
  'widget.save': 'Save widget settings',
  'common.saving': 'Saving…',
  'app.napEnded': 'Nap ended',
  'app.napStarted': 'Nap started',
  'app.logged': '{activity} logged',
  'app.estimateAdded': '{activity} added at estimated time',
  'app.deleteTitle': 'Delete this log?',
  'app.deleteMessage': '{activity} at {time}',
  'app.cancel': 'Cancel',
  'app.delete': 'Delete',
  'app.routineSaved': 'Routine saved',
  'app.notificationsOff': 'Notifications are off, so reminders could not be scheduled.',
  'app.reminderError': 'Puptime could not update reminders. Try editing the routine again.',
  'schedule.title': 'Schedule',
  'schedule.status.logged': 'Logged',
  'schedule.status.due': 'Due now',
  'schedule.status.missed': 'Missed',
  'schedule.status.upcoming': 'Upcoming',
  'schedule.saveErrorTitle': 'Couldn’t save the routine',
  'schedule.saveErrorBody': 'Your previous routine is still available. Please try again.',
  'schedule.notificationsOff': 'Notifications are off',
  'schedule.notificationsBody': 'Allow Puptime notifications in system settings to use daily routine reminders.',
  'schedule.notNow': 'Not now',
  'schedule.openSettings': 'Open settings',
  'schedule.reminderErrorTitle': 'Couldn’t enable reminders',
  'schedule.reminderErrorBody': 'Please try again from this routine entry.',
  'schedule.removeTitle': 'Remove this time?',
  'schedule.entryAt': '{activity} at {time}',
  'schedule.remove': 'Remove',
  'schedule.removeErrorTitle': 'Couldn’t remove the time',
  'schedule.removeErrorBody': 'Your routine has not changed. Please try again.',
  'schedule.suggestionErrorTitle': 'Couldn’t use the suggested routine',
  'schedule.suggestionErrorBody': 'Your current routine is still available. Please try again.',
  'schedule.suggestedTimes': '{count} times from {days} recorded days',
  'schedule.needDays': '{count} more recorded days needed for suggestions',
  'schedule.noPattern': 'No repeated pattern yet',
  'schedule.previewA11y': 'Preview {count} suggested routine times',
  'schedule.previewButton': 'Review suggestions',
  'schedule.loggedProgress': '{completed} of {total} logged',
  'schedule.dueOne': '1 activity is due now',
  'schedule.dueMany': '{count} activities are due now',
  'schedule.missedOne': '1 missed window',
  'schedule.missedMany': '{count} missed windows',
  'schedule.everythingLogged': 'All planned activities logged',
  'schedule.nextAhead': 'Next activity is later',
  'schedule.todayPlan': 'Today’s plan',
  'schedule.emptyTitle': 'No times yet',
  'schedule.editA11y': 'Edit {activity} at {time}, {status}{reminder}',
  'schedule.reminderOn': ', daily reminder on',
  'schedule.removeA11y': 'Remove {activity} at {time}',
  'schedule.addA11y': 'Add a routine time',
  'schedule.addTime': 'Add a time',
  'schedule.suggestionTitle': 'Suggested schedule',
  'schedule.suggestionSubtitle': 'Uses activities logged on most of {days} recorded days from the last {period} days. Times are rounded to 15 minutes. Not veterinary advice.',
  'schedule.closeSuggestion': 'Close suggested routine',
  'schedule.replaceCurrent': 'Replaces your {count} current times. ',
  'schedule.createRoutine': 'Creates your routine. ',
  'schedule.remindersStayOff': 'Reminders start off.',
  'schedule.usingRoutine': 'Using routine…',
  'schedule.useRoutine': 'Use this routine',
  'schedule.keepRoutine': 'Keep current routine',
  'schedule.editTime': 'Edit time',
  'schedule.close': 'Close',
  'schedule.activity': 'ACTIVITY',
  'schedule.time': 'TIME',
  'schedule.dailyReminder': 'Daily reminder',
  'schedule.reminderA11y': 'Daily reminder for this routine entry',
  'schedule.saveTime': 'Save time',
  'insights.activity': 'activity',
  'insights.selectedActivity': 'selected activity',
  'insights.noSelected': 'No activities selected',
  'insights.allActivity': 'All activity',
  'insights.timing': '{activities} timing',
  'insights.activityCount': '{count} activities',
  'insights.pointWindow': '{activity} in the {start} to {end} window',
  'insights.durationWindow': '{activity} from about {start} to {end}',
  'insights.perDay': '{value}/day',
  'insights.eachRecordedDay': '{count} on each recorded day',
  'insights.rangePerDay': '{minimum}–{maximum} per recorded day',
  'insights.noLogsYet': 'No {activity} logs yet',
  'insights.needAnotherLog': 'Need another log',
  'insights.middleHalf': 'Middle half: {lower}–{upper}',
  'insights.gapsObserved': '{count} gaps observed',
  'insights.logCount': '{count} logs',
  'insights.typicalGap': 'TYPICAL GAP',
  'insights.noLogged': 'No {activity} logged',
  'insights.noActivitySelected': 'No activity selected',
  'insights.today': 'TODAY',
  'insights.currentTime': 'Current time {time}',
  'insights.decrease': 'Decrease {control}',
  'insights.increase': 'Increase {control}',
  'insights.thisMonth': 'This month',
  'insights.monthA11y': '{month}. {average} {activity} logs per recorded day. {logs} logs across {days} recorded days.',
  'insights.monthDetail': '{logs} logs · {days} days with activity',
  'insights.exportErrorTitle': 'Couldn’t export activity',
  'insights.exportErrorBody': 'Please try again. Your Puptime data is unchanged.',
  'insights.estimateErrorTitle': 'Couldn’t add this estimate',
  'insights.estimateErrorBody': 'Your activity history is unchanged. Please try again.',
  'insights.title': 'Insights',
  'insights.frequencyTitle': 'Frequency',
  'insights.frequencyCaption': '{recorded}/{period} days with logs · not a target',
  'insights.gapsTitle': 'Possible gaps',
  'insights.mealName': 'Meal',
  'insights.around': 'around {time}',
  'insights.aboutRange': 'about {start}–{end}',
  'insights.possibleNap': 'Nap may be missing',
  'insights.mayBeUnlogged': '{activity} may be missing',
  'insights.seenEvidence': 'Logged near this time on {observed} of {compared} other recorded days.',
  'insights.addEstimateA11y': 'Add {activity} at the estimated time',
  'insights.adding': 'Adding…',
  'insights.addLog': 'Add log',
  'insights.needGapDays': '{count} more recorded days needed to check for gaps.',
  'insights.noGaps': 'No likely gaps in the last {count} days.',
  'insights.all': 'All',
  'insights.clearFilters': 'Clear all activity filters',
  'insights.selectFilters': 'Select all activity filters',
  'insights.hideTiming': 'Hide {activity} timing',
  'insights.showTiming': 'Show {activity} timing',
  'insights.panelCaption': '{range} · {count} logs',
  'insights.timeWidth': 'Time width',
  'insights.dayHeight': 'Days shown',
  'insights.showEarlier': 'Show earlier dates',
  'insights.earlier': 'Earlier',
  'insights.showNewer': 'Show newer dates',
  'insights.newer': 'Newer',
  'insights.chooseActivity': 'Choose at least one activity above to show it on the timeline.',
  'insights.noRangeLogs': 'No {activity} logged in this date range.',
  'insights.historyTitle': 'By month',
  'insights.showRecentMonths': 'Show recent months',
  'insights.showAllMonths': 'Show all {count} months',
  'insights.exportA11y': 'Export all activity as CSV',
  'insights.noExport': 'No activity to export',
  'insights.exportHint': 'Opens the system share sheet',
  'insights.preparingExport': 'Preparing export…',
  'insights.exportButton': 'Export CSV',
  'timeline.title': 'Timeline',
  'timeline.date': 'DATE',
  'timeline.zoomOut': 'Zoom out time',
  'timeline.zoomIn': 'Zoom in time',
  'timeline.range': '{range} · {count} logs',
  'timeline.loadEarlier': 'Load earlier days',
  'timeline.loadingEarlier': 'Loading earlier days',
  'timeline.historyStart': 'No earlier logged days',
} as const;

export type MessageKey = keyof typeof english;
type Dictionary = Record<MessageKey, string>;

const simplifiedChinese: Dictionary = {
  'language.system': '跟随系统',
  'language.systemDetail': '使用此设备的语言',
  'language.en': '英语',
  'language.zh-Hans': '简体中文',
  'language.es': '西班牙语',
  'nav.log': '今天',
  'nav.timeline': '时间线',
  'nav.insights': '分析',
  'nav.schedule': '日程',
  'settings.title': '设置',
  'settings.back': '返回今天',
  'settings.personalization': '个性化',
  'settings.theme': '主题',
  'settings.themeDetail': '颜色和布局',
  'settings.language': '语言',
  'settings.widget': '小组件',
  'settings.widgetDetail': '选择 2–4 个动作。',
  'settings.notifications': '通知',
  'settings.notificationPermission': '通知权限',
  'settings.permissionGranted': '已允许',
  'settings.permissionRequestable': '提醒和记录确认需要此权限',
  'settings.permissionBlocked': '通知已在设备设置中关闭',
  'settings.allowNotifications': '允许通知',
  'settings.routineReminders': '日程提醒',
  'settings.routineRemindersDetail': '已开启 {count} 项',
  'settings.manageSchedule': '管理日程',
  'settings.reminderTiming': '提醒时间',
  'settings.reminderTimingDetail': '用于所有日程提醒。',
  'settings.atTime': '准时',
  'settings.minutesBefore': '提前 {count} 分钟',
  'settings.pottyNudges': '如厕提醒',
  'settings.pottyNudgesDetail': '根据最近的记录计时。记录尿尿后会重新计时。',
  'settings.afterPeeReminder': '尿尿之后',
  'settings.afterPeeReminderDetail': '可能又该尿尿时提醒。',
  'settings.afterMealReminder': '吃饭之后',
  'settings.afterMealReminderDetail': '饭后可能需要如厕时提醒。',
  'settings.widgetConfirmations': '小组件记录确认',
  'settings.widgetConfirmationsDetail': '每次用小组件记录后显示通知。',
  'settings.saveErrorTitle': '无法保存设置',
  'settings.saveErrorBody': '原设置已保留，请重试。',
  'settings.themePickerTitle': '选择主题',
  'settings.languagePickerTitle': '选择语言',
  'settings.closePicker': '关闭设置选择器',
  'settings.guide': '应用指南',
  'settings.guideDetail': '了解记录、日程和提醒',
  'onboarding.skip': '跳过',
  'onboarding.progress': '第 {step} 步，共 4 步',
  'onboarding.logTitle': '一键记录日常。',
  'onboarding.logBody': '尿尿、吃饭、散步和午睡，轻点即可记录。',
  'onboarding.preview': '示例',
  'onboarding.todayPreview': '今天',
  'onboarding.mealPreview': '吃饭',
  'onboarding.peePreview': '尿尿',
  'onboarding.walkPreview': '散步',
  'onboarding.timelineTitle': '看清每天的规律。',
  'onboarding.timelineBody': '按天查看记录发生的时间，放大可看细节。',
  'onboarding.timelineYesterday': '昨天',
  'onboarding.timelineEarlier': '之前',
  'onboarding.routineTitle': '安排一天。',
  'onboarding.routineBody': '在日程中添加时间，按需开启提醒。',
  'onboarding.routinePreview': '每日安排',
  'onboarding.nudgeTitle': '及时收到提醒。',
  'onboarding.nudgeBody': '如厕提醒和日程提醒，按需开启。',
  'onboarding.notificationExampleTitle': '该如厕了吗？',
  'onboarding.notificationExampleBody': '饭后 30 分钟。',
  'onboarding.routineDetail': '日程活动前',
  'onboarding.widgetDetail': '可选，确认主屏幕记录',
  'onboarding.changeLater': '随时在设置中调整。',
  'onboarding.continue': '下一步',
  'onboarding.start': '开始记录',
  'onboarding.allow': '允许通知',
  'onboarding.later': '暂不',
  'onboarding.back': '返回',
  'notifications.reminderSoon': '{minutes} 分钟后该{activity}了',
  'notifications.reminderNow': '该{activity}了',
  'notifications.reminderBody': '计划时间 {time}。轻点记录。',
  'notifications.delayMinutes': '{count} 分钟',
  'notifications.delayOneHour': '1 小时',
  'notifications.delayHours': '{count} 小时',
  'notifications.afterPeeTitle': '该出去尿尿了吗？',
  'notifications.afterPeeBody': '距离上次尿尿已经 {delay}，小狗可能又需要出去了。',
  'notifications.afterMealTitle': '饭后该出去尿尿了吗？',
  'notifications.afterMealBody': '距离上次吃饭已经 {delay}，小狗可能需要出去尿尿。',
  'notifications.widgetLoggedTitle': '活动已记录',
  'notifications.widgetLoggedBody': '已通过小组件记录：{activity}。',
  'notifications.addNote': '添加备注',
  'notifications.editDetails': '编辑详情',
  'notifications.saveNote': '保存',
  'notifications.notePlaceholder': '添加备注',
  'theme.meadow.detail': '柔和色彩 · 圆角',
  'theme.sunrise.detail': '暖色 · 紧凑',
  'theme.midnight.detail': '深色 · 宽松',
  'theme.paper.detail': '黑白 · 方角',
  'theme.bubblegum.detail': '粉色 · 圆角',
  'theme.blueprint.detail': '蓝色网格 · 紧凑',
  'theme.trail.detail': '大地色 · 方角',
  'theme.tide.detail': '蓝绿色 · 圆角',
  'theme.plum.detail': '紫色 · 方角',
  'theme.contrast.detail': '黑白 · 高对比度',
  'event.pee': '尿尿',
  'event.poop': '便便',
  'event.meal': '吃饭',
  'event.pottyTrip': '外出如厕',
  'event.walk': '散步',
  'event.nap': '小睡',
  'event.custom': '其他',
  'eventPast.pee': '尿尿了',
  'eventPast.poop': '便便了',
  'eventPast.meal': '吃过饭',
  'eventPast.pottyTrip': '外出如厕了',
  'eventPast.walk': '散过步',
  'eventPast.nap': '开始小睡',
  'eventPast.custom': '其他活动',
  'eventPast.napRunning': '正在小睡',
  'eventPast.napped': '睡了一觉',
  'time.justNow': '刚刚',
  'time.minutes': '{count} 分钟',
  'time.hours': '{count} 小时',
  'time.days': '{count} 天',
  'time.minutesAgo': '{count} 分钟前',
  'time.hoursAgo': '{count} 小时前',
  'time.daysAgo': '{count} 天前',
  'quick.endNap': '结束小睡',
  'quick.endNapA11y': '结束当前小睡',
  'quick.endNapHint': '保存小睡结束时间',
  'quick.logAction': '记录{activity}',
  'quick.logHint': '把当前时间添加到活动记录',
  'quick.running': '已进行 {time}',
  'quick.another': '其他活动',
  'quick.anotherHint': '打开常用和自定义活动',
  'quick.logAnother': '记录其他活动',
  'quick.customActivity': '自定义活动',
  'quick.customPlaceholder': '例如：梳毛',
  'quick.customName': '自定义活动名称',
  'quick.customLogA11y': '立即记录自定义活动',
  'quick.logNow': '立即记录',
  'quick.close': '关闭活动选择器',
  'quick.water': '喝水',
  'quick.accident': '意外',
  'quick.play': '玩耍',
  'quick.training': '训练',
  'quick.crate': '进笼',
  'quick.medicine': '吃药',
  'routine.build': '添加日程',
  'routine.buildDetail': '添加时间和可选提醒。',
  'routine.due': '现在该{activity}了',
  'routine.at': '{time} · {activity}',
  'routine.missedOne': '错过了 1 个日程时间',
  'routine.missedMany': '错过了 {count} 个日程时间',
  'routine.complete': '日程已完成',
  'routine.plannedFor': '计划时间 {time}',
  'routine.inMinutes': '{count} 分钟后',
  'routine.inHours': '{count} 小时后',
  'routine.inHoursMinutes': '{hours} 小时 {minutes} 分钟后',
  'routine.now': '现在',
  'routine.progress': '已完成 {completed}/{total}',
  'routine.logged': '已记录 {completed}/{total} 项计划活动',
  'routine.openHint': '打开每日日程',
  'common.undo': '撤销',
  'common.addNote': '添加备注',
  'common.addNoteA11y': '为这条记录添加备注',
  'common.done': '完成',
  'eventRow.now': '现在',
  'eventRow.running': '进行中',
  'eventRow.widget': '小组件',
  'eventRow.app': '应用',
  'eventRow.edit': '编辑{activity}记录',
  'eventRow.editNapHint': '打开日期、时间和备注控件',
  'eventRow.editHint': '打开活动、日期、时间和备注控件',
  'eventRow.delete': '删除 {time} 的{activity}记录',
  'note.listeningAnnouncement': '正在聆听备注',
  'note.transcribeErrorTitle': '无法转写',
  'note.accessOff': '麦克风或语音权限已关闭。你可以在设置中开启，或直接输入备注。',
  'note.tryAgain': '请重试麦克风，或直接输入备注。',
  'note.unavailableTitle': '语音备注不可用',
  'note.unavailableBody': '此手机不支持语音识别，你仍可输入备注。',
  'note.permissionTitle': '需要麦克风权限',
  'note.permissionBody': '请允许麦克风和语音权限来听写备注，你仍可输入备注。',
  'note.startError': '语音识别无法启动，你仍可输入备注。',
  'note.label': '此记录的备注',
  'note.placeholder': '例如：刚玩耍结束',
  'note.stopDictating': '停止听写备注',
  'note.dictate': '听写备注',
  'note.listeningHint': '正在聆听…完成后请点停止。',
  'log.customizeWidgetA11y': '自定义主屏幕小组件',
  'log.changeAppearanceA11y': '更改外观和语言',
  'log.openSettingsA11y': '打开设置',
  'log.activity': '记录',
  'log.filter.all': '全部',
  'log.filter.potty': '如厕',
  'log.filter.meals': '吃饭',
  'log.filter.walks': '散步',
  'log.filter.naps': '小睡',
  'log.filter.other': '其他',
  'log.showFilter': '显示{filter}活动',
  'log.showRecentA11y': '显示最近 {count} 天的活动',
  'log.viewAllA11y': '查看全部活动记录，包括 {count} 条更早的记录',
  'log.showRecent': '显示最近 {count} 天',
  'log.viewAll': '查看更早的 {count} 条记录',
  'log.toggleDayA11y': '{day}，记录数：{count}',
  'log.today': '今天',
  'log.yesterday': '昨天',
  'log.emptyTitle': '暂无活动',
  'log.emptyRecentTitle': '最近 {count} 天没有活动记录',
  'log.emptyFilteredTitle': '还没有{filter}记录',
  'log.saveErrorTitle': '无法保存更改',
  'log.saveErrorBody': '点按保存提示重试。',
  'log.widgetErrorTitle': '无法保存小组件设置',
  'log.tryAgain': '请重试。',
  'editor.editNap': '编辑小睡',
  'editor.editLog': '编辑记录',
  'editor.close': '关闭记录编辑器',
  'editor.retryA11y': '无法保存更改，立即重试',
  'editor.retry': '无法保存，点此重试。',
  'editor.customNameStatus': '添加自定义名称后才能保存。',
  'editor.saving': '正在保存更改…',
  'editor.activity': '活动',
  'editor.changeActivity': '将活动改为{activity}',
  'editor.customName': '自定义名称',
  'editor.customNameA11y': '自定义活动名称',
  'editor.customNameHint': '必填。输入后会自动保存更改。',
  'editor.customPlaceholder': '例如：梳毛',
  'editor.customInvalid': '请输入活动名称。',
  'editor.now': '现在',
  'editor.inProgress': '进行中',
  'editor.start': '开始',
  'editor.end': '结束',
  'editor.date': '日期',
  'editor.time': '时间',
  'editor.editNapTime': '编辑小睡{field}时间',
  'editor.quickBackdate': '快速回溯',
  'editor.setField': '设置{field}',
  'editor.backdate': '将时间设为 {count} 分钟前',
  'editor.setNow': '将时间设为现在',
  'editor.minutesAgo': '{count} 分钟前',
  'editor.dateTime': '日期和时间',
  'editor.chooseDate': '选择{field}日期，当前为 {date}',
  'editor.chooseTime': '选择{field}准确时间，当前为 {time}',
  'editor.finishPicker': '完成选择{picker}',
  'editor.note': '备注',
  'widget.title': '自定义小组件',
  'widget.subtitle': '选择 2–4 个动作。',
  'widget.close': '关闭小组件设置',
  'widget.addAction': '将{activity}添加到小组件',
  'widget.removeAction': '从小组件移除{activity}',
  'widget.keepTwo': '至少保留两个小组件动作。',
  'widget.removeFirst': '请先移除另一个动作。',
  'widget.napHint': '小睡进行时会显示此动作。',
  'widget.save': '保存小组件设置',
  'common.saving': '正在保存…',
  'app.napEnded': '小睡已结束',
  'app.napStarted': '小睡已开始',
  'app.logged': '已记录{activity}',
  'app.estimateAdded': '已在推测时间添加{activity}',
  'app.deleteTitle': '删除这条记录？',
  'app.deleteMessage': '{time} · {activity}',
  'app.cancel': '取消',
  'app.delete': '删除',
  'app.routineSaved': '日程已保存',
  'app.notificationsOff': '通知已关闭，因此无法安排提醒。',
  'app.reminderError': 'Puptime 无法更新提醒。请再次编辑日程。',
  'schedule.title': '日程',
  'schedule.status.logged': '已记录',
  'schedule.status.due': '现在该做',
  'schedule.status.missed': '已错过',
  'schedule.status.upcoming': '即将到来',
  'schedule.saveErrorTitle': '无法保存日程',
  'schedule.saveErrorBody': '之前的日程仍然可用，请重试。',
  'schedule.notificationsOff': '通知已关闭',
  'schedule.notificationsBody': '请在系统设置中允许 Puptime 通知，以使用每日提醒。',
  'schedule.notNow': '暂不',
  'schedule.openSettings': '打开设置',
  'schedule.reminderErrorTitle': '无法启用提醒',
  'schedule.reminderErrorBody': '请从此日程项目中重试。',
  'schedule.removeTitle': '移除这个时间？',
  'schedule.entryAt': '{time} · {activity}',
  'schedule.remove': '移除',
  'schedule.removeErrorTitle': '无法移除时间',
  'schedule.removeErrorBody': '日程未发生变化，请重试。',
  'schedule.suggestionErrorTitle': '无法使用建议日程',
  'schedule.suggestionErrorBody': '当前日程仍然可用，请重试。',
  'schedule.suggestedTimes': '{count} 个时间 · 来自 {days} 个记录日',
  'schedule.needDays': '还需 {count} 个记录日才能生成建议',
  'schedule.noPattern': '尚未发现重复规律',
  'schedule.previewA11y': '预览 {count} 个建议日程时间',
  'schedule.previewButton': '查看建议',
  'schedule.loggedProgress': '已记录 {completed}/{total}',
  'schedule.dueOne': '现在有 1 项活动该进行了',
  'schedule.dueMany': '现在有 {count} 项活动该进行了',
  'schedule.missedOne': '错过了 1 个时间段',
  'schedule.missedMany': '错过了 {count} 个时间段',
  'schedule.everythingLogged': '所有计划活动均已记录',
  'schedule.nextAhead': '下一项活动稍后开始',
  'schedule.todayPlan': '今日计划',
  'schedule.emptyTitle': '暂无时间',
  'schedule.editA11y': '编辑 {time} 的{activity}，{status}{reminder}',
  'schedule.reminderOn': '，每日提醒已开启',
  'schedule.removeA11y': '移除 {time} 的{activity}',
  'schedule.addA11y': '添加日程时间',
  'schedule.addTime': '添加时间',
  'schedule.suggestionTitle': '建议日程',
  'schedule.suggestionSubtitle': '使用最近 {period} 天中大多数记录日都出现的活动，共 {days} 个记录日。时间取整到 15 分钟。这不是兽医建议。',
  'schedule.closeSuggestion': '关闭建议日程',
  'schedule.replaceCurrent': '将替换当前 {count} 个时间。',
  'schedule.createRoutine': '将创建日程。',
  'schedule.remindersStayOff': '提醒默认关闭。',
  'schedule.usingRoutine': '正在使用日程…',
  'schedule.useRoutine': '使用此日程',
  'schedule.keepRoutine': '保留当前日程',
  'schedule.editTime': '编辑时间',
  'schedule.close': '关闭',
  'schedule.activity': '活动',
  'schedule.time': '时间',
  'schedule.dailyReminder': '每日提醒',
  'schedule.reminderA11y': '此日程项目的每日提醒',
  'schedule.saveTime': '保存时间',
  'insights.activity': '活动',
  'insights.selectedActivity': '所选活动',
  'insights.noSelected': '未选择活动',
  'insights.allActivity': '全部活动',
  'insights.timing': '{activities}时间',
  'insights.activityCount': '{count} 项活动',
  'insights.pointWindow': '{activity}出现在 {start} 到 {end} 之间',
  'insights.durationWindow': '{activity}大约从 {start} 持续到 {end}',
  'insights.perDay': '{value}/天',
  'insights.eachRecordedDay': '每个记录日 {count} 次',
  'insights.rangePerDay': '每个记录日 {minimum}–{maximum} 次',
  'insights.noLogsYet': '还没有{activity}记录',
  'insights.needAnotherLog': '还需要一条记录',
  'insights.middleHalf': '中间一半：{lower}–{upper}',
  'insights.gapsObserved': '观察到 {count} 个间隔',
  'insights.logCount': '{count} 条记录',
  'insights.typicalGap': '典型间隔',
  'insights.noLogged': '未记录{activity}',
  'insights.noActivitySelected': '未选择活动',
  'insights.today': '今天',
  'insights.currentTime': '当前时间 {time}',
  'insights.decrease': '减小{control}',
  'insights.increase': '增大{control}',
  'insights.thisMonth': '本月',
  'insights.monthA11y': '{month}。每个记录日平均 {average} 条{activity}记录。{days} 个记录日共 {logs} 条。',
  'insights.monthDetail': '{logs} 条记录 · {days} 个活动日',
  'insights.exportErrorTitle': '无法导出活动',
  'insights.exportErrorBody': '请重试。Puptime 数据未发生变化。',
  'insights.estimateErrorTitle': '无法添加这条推测记录',
  'insights.estimateErrorBody': '活动历史未发生变化，请重试。',
  'insights.title': '分析',
  'insights.frequencyTitle': '频率',
  'insights.frequencyCaption': '{period} 天中有 {recorded} 天有记录 · 非目标',
  'insights.gapsTitle': '可能漏记',
  'insights.mealName': '吃饭',
  'insights.around': '约 {time}',
  'insights.aboutRange': '约 {start}–{end}',
  'insights.possibleNap': '可能漏记小睡',
  'insights.mayBeUnlogged': '可能漏记{activity}',
  'insights.seenEvidence': '在另外 {compared} 个记录日中，有 {observed} 天在相近时间记录。',
  'insights.addEstimateA11y': '在推测时间添加{activity}',
  'insights.adding': '正在添加…',
  'insights.addLog': '添加记录',
  'insights.needGapDays': '还需 {count} 个记录日才能检查漏记。',
  'insights.noGaps': '最近 {count} 天没有明显漏记。',
  'insights.all': '全部',
  'insights.clearFilters': '清除全部活动筛选',
  'insights.selectFilters': '选择全部活动筛选',
  'insights.hideTiming': '隐藏{activity}时间',
  'insights.showTiming': '显示{activity}时间',
  'insights.panelCaption': '{range} · {count} 条记录',
  'insights.timeWidth': '时间宽度',
  'insights.dayHeight': '显示天数',
  'insights.showEarlier': '显示更早日期',
  'insights.earlier': '更早',
  'insights.showNewer': '显示较新日期',
  'insights.newer': '较新',
  'insights.chooseActivity': '请至少选择一项活动以显示在时间线上。',
  'insights.noRangeLogs': '此日期范围内没有{activity}记录。',
  'insights.historyTitle': '按月查看',
  'insights.showRecentMonths': '显示最近月份',
  'insights.showAllMonths': '显示全部 {count} 个月',
  'insights.exportA11y': '将全部活动导出为 CSV',
  'insights.noExport': '没有可导出的活动',
  'insights.exportHint': '打开系统分享面板',
  'insights.preparingExport': '正在准备导出…',
  'insights.exportButton': '导出 CSV',
  'timeline.title': '时间线',
  'timeline.date': '日期',
  'timeline.zoomOut': '缩小时间',
  'timeline.zoomIn': '放大时间',
  'timeline.range': '{range} · {count} 条记录',
  'timeline.loadEarlier': '加载更早日期',
  'timeline.loadingEarlier': '正在加载更早日期',
  'timeline.historyStart': '没有更早的记录日期',
};

const spanish: Dictionary = {
  'language.system': 'Sistema',
  'language.systemDetail': 'Usar el idioma del dispositivo',
  'language.en': 'Inglés',
  'language.zh-Hans': 'Chino simplificado',
  'language.es': 'Español',
  'nav.log': 'Hoy',
  'nav.timeline': 'Cronología',
  'nav.insights': 'Análisis',
  'nav.schedule': 'Rutina',
  'settings.title': 'Ajustes',
  'settings.back': 'Volver a Hoy',
  'settings.personalization': 'PERSONALIZACIÓN',
  'settings.theme': 'Tema',
  'settings.themeDetail': 'Colores y diseño',
  'settings.language': 'Idioma',
  'settings.widget': 'WIDGET',
  'settings.widgetDetail': 'Elige entre 2 y 4 acciones.',
  'settings.notifications': 'NOTIFICACIONES',
  'settings.notificationPermission': 'Acceso a notificaciones',
  'settings.permissionGranted': 'Permitido',
  'settings.permissionRequestable': 'Necesario para recordatorios y confirmaciones',
  'settings.permissionBlocked': 'Las notificaciones están desactivadas en el dispositivo',
  'settings.allowNotifications': 'Permitir notificaciones',
  'settings.routineReminders': 'Recordatorios de rutina',
  'settings.routineRemindersDetail': '{count} activados',
  'settings.manageSchedule': 'Gestionar rutina',
  'settings.reminderTiming': 'Momento del recordatorio',
  'settings.reminderTimingDetail': 'Se usa en todos los recordatorios.',
  'settings.atTime': 'A la hora',
  'settings.minutesBefore': '{count} min antes',
  'settings.pottyNudges': 'Avisos para ir al baño',
  'settings.pottyNudgesDetail': 'Se basan en el último registro. Registrar un pipí reinicia los tiempos.',
  'settings.afterPeeReminder': 'Después de hacer pipí',
  'settings.afterPeeReminderDetail': 'Avisa cuando quizá necesite volver a salir.',
  'settings.afterMealReminder': 'Después de comer',
  'settings.afterMealReminderDetail': 'Avisa de una posible salida al baño tras comer.',
  'settings.widgetConfirmations': 'Confirmaciones del widget',
  'settings.widgetConfirmationsDetail': 'Muestra una notificación tras cada registro del widget.',
  'settings.saveErrorTitle': 'No se pudieron guardar los ajustes',
  'settings.saveErrorBody': 'Se conservaron los ajustes anteriores. Inténtalo de nuevo.',
  'settings.themePickerTitle': 'Elige un tema',
  'settings.languagePickerTitle': 'Elige un idioma',
  'settings.closePicker': 'Cerrar selector de ajustes',
  'settings.guide': 'Guía de la app',
  'settings.guideDetail': 'Conoce los registros, la rutina y los avisos',
  'onboarding.skip': 'Omitir',
  'onboarding.progress': 'Paso {step} de 4',
  'onboarding.logTitle': 'Registra lo importante.',
  'onboarding.logBody': 'Pipí, comidas, paseos y siestas con un toque.',
  'onboarding.preview': 'EJEMPLO',
  'onboarding.todayPreview': 'Hoy',
  'onboarding.mealPreview': 'Comida',
  'onboarding.peePreview': 'Pipí',
  'onboarding.walkPreview': 'Paseo',
  'onboarding.timelineTitle': 'Ve el patrón.',
  'onboarding.timelineBody': 'Mira cuándo pasó cada cosa. Amplía para ver detalles.',
  'onboarding.timelineYesterday': 'Ayer',
  'onboarding.timelineEarlier': 'Antes',
  'onboarding.routineTitle': 'Organiza el día.',
  'onboarding.routineBody': 'Añade horas a Rutina y activa avisos cuando quieras.',
  'onboarding.routinePreview': 'Rutina diaria',
  'onboarding.nudgeTitle': 'Recibe avisos útiles.',
  'onboarding.nudgeBody': 'Avisos para salir y para tu rutina.',
  'onboarding.notificationExampleTitle': '¿Hora de salir?',
  'onboarding.notificationExampleBody': '30 minutos después de comer.',
  'onboarding.routineDetail': 'Antes de lo planeado',
  'onboarding.widgetDetail': 'Opcional, para registros del widget',
  'onboarding.changeLater': 'Cambia los avisos en Ajustes.',
  'onboarding.continue': 'Siguiente',
  'onboarding.start': 'Empezar a registrar',
  'onboarding.allow': 'Permitir notificaciones',
  'onboarding.later': 'Ahora no',
  'onboarding.back': 'Atrás',
  'notifications.reminderSoon': '{activity} en {minutes} min',
  'notifications.reminderNow': 'Es hora de {activity}',
  'notifications.reminderBody': 'Programado para las {time}. Toca para registrarlo.',
  'notifications.delayMinutes': '{count} minutos',
  'notifications.delayOneHour': '1 hora',
  'notifications.delayHours': '{count} horas',
  'notifications.afterPeeTitle': '¿Hora de salir al baño?',
  'notifications.afterPeeBody': 'Han pasado {delay} desde el último pipí. Puede que necesite volver a salir.',
  'notifications.afterMealTitle': '¿Hora de salir después de comer?',
  'notifications.afterMealBody': 'Han pasado {delay} desde la última comida. Puede que necesite salir al baño.',
  'notifications.widgetLoggedTitle': 'Actividad registrada',
  'notifications.widgetLoggedBody': 'Se guardó {activity} desde el widget.',
  'notifications.addNote': 'Añadir nota',
  'notifications.editDetails': 'Editar detalles',
  'notifications.saveNote': 'Guardar',
  'notifications.notePlaceholder': 'Añadir una nota',
  'theme.meadow.detail': 'Colores suaves · redondeado',
  'theme.sunrise.detail': 'Colores cálidos · compacto',
  'theme.midnight.detail': 'Colores oscuros · amplio',
  'theme.paper.detail': 'Blanco y negro · cuadrado',
  'theme.bubblegum.detail': 'Rosa · redondeado',
  'theme.blueprint.detail': 'Cuadrícula azul · compacta',
  'theme.trail.detail': 'Tonos tierra · angular',
  'theme.tide.detail': 'Azul verdoso · redondeado',
  'theme.plum.detail': 'Morado · angular',
  'theme.contrast.detail': 'Blanco y negro · alto contraste',
  'event.pee': 'Pipí',
  'event.poop': 'Caca',
  'event.meal': 'Comida',
  'event.pottyTrip': 'Salida al baño',
  'event.walk': 'Paseo',
  'event.nap': 'Siesta',
  'event.custom': 'Otro',
  'eventPast.pee': 'Hizo pipí',
  'eventPast.poop': 'Hizo caca',
  'eventPast.meal': 'Comió',
  'eventPast.pottyTrip': 'Salió al baño',
  'eventPast.walk': 'Salió de paseo',
  'eventPast.nap': 'Empezó una siesta',
  'eventPast.custom': 'Otra actividad',
  'eventPast.napRunning': 'Siesta en curso',
  'eventPast.napped': 'Durmió la siesta',
  'time.justNow': 'ahora mismo',
  'time.minutes': '{count} min',
  'time.hours': '{count} h',
  'time.days': '{count} d',
  'time.minutesAgo': 'hace {count} min',
  'time.hoursAgo': 'hace {count} h',
  'time.daysAgo': 'hace {count} d',
  'quick.endNap': 'Terminar siesta',
  'quick.endNapA11y': 'Terminar la siesta actual',
  'quick.endNapHint': 'Guarda la hora de fin de la siesta',
  'quick.logAction': 'Registrar {activity}',
  'quick.logHint': 'Añade la hora actual al registro de actividad',
  'quick.running': '{time} en curso',
  'quick.another': 'Otra actividad',
  'quick.anotherHint': 'Abre actividades habituales y personalizadas',
  'quick.logAnother': 'Registrar otra actividad',
  'quick.customActivity': 'ACTIVIDAD PERSONALIZADA',
  'quick.customPlaceholder': 'p. ej., Cepillado',
  'quick.customName': 'Nombre de la actividad personalizada',
  'quick.customLogA11y': 'Registrar ahora la actividad personalizada',
  'quick.logNow': 'Registrar ahora',
  'quick.close': 'Cerrar selector de actividad',
  'quick.water': 'Agua',
  'quick.accident': 'Accidente',
  'quick.play': 'Juego',
  'quick.training': 'Entrenamiento',
  'quick.crate': 'Jaula',
  'quick.medicine': 'Medicina',
  'routine.build': 'Añadir rutina',
  'routine.buildDetail': 'Añade horas y recordatorios opcionales.',
  'routine.due': 'Es hora de {activity}',
  'routine.at': '{activity} a las {time}',
  'routine.missedOne': '1 hora de la rutina perdida',
  'routine.missedMany': '{count} horas de la rutina perdidas',
  'routine.complete': 'Rutina completada',
  'routine.plannedFor': 'Programado para las {time}',
  'routine.inMinutes': 'en {count} min',
  'routine.inHours': 'en {count} h',
  'routine.inHoursMinutes': 'en {hours} h {minutes} min',
  'routine.now': 'ahora',
  'routine.progress': '{completed} de {total} completados',
  'routine.logged': '{completed} de {total} actividades previstas registradas',
  'routine.openHint': 'Abre la rutina diaria',
  'common.undo': 'Deshacer',
  'common.addNote': 'Añadir nota',
  'common.addNoteA11y': 'Añadir una nota a este registro',
  'common.done': 'Listo',
  'eventRow.now': 'ahora',
  'eventRow.running': 'en curso',
  'eventRow.widget': 'Widget',
  'eventRow.app': 'App',
  'eventRow.edit': 'Editar registro de {activity}',
  'eventRow.editNapHint': 'Abre los controles de fecha, hora y nota',
  'eventRow.editHint': 'Abre los controles de actividad, fecha, hora y nota',
  'eventRow.delete': 'Eliminar {activity} a las {time}',
  'note.listeningAnnouncement': 'Escuchando la nota',
  'note.transcribeErrorTitle': 'No se pudo transcribir',
  'note.accessOff': 'El acceso al micrófono o al reconocimiento de voz está desactivado. Puedes activarlo en Ajustes o escribir la nota.',
  'note.tryAgain': 'Prueba de nuevo el micrófono o escribe la nota.',
  'note.unavailableTitle': 'Notas de voz no disponibles',
  'note.unavailableBody': 'El reconocimiento de voz no está disponible en este teléfono. Aún puedes escribir la nota.',
  'note.permissionTitle': 'Se necesita acceso al micrófono',
  'note.permissionBody': 'Permite el acceso al micrófono y al reconocimiento de voz para dictar notas. Aún puedes escribir la nota.',
  'note.startError': 'No se pudo iniciar el reconocimiento de voz. Aún puedes escribir la nota.',
  'note.label': 'Nota de este registro',
  'note.placeholder': 'p. ej., Justo después de jugar',
  'note.stopDictating': 'Detener el dictado de la nota',
  'note.dictate': 'Dictar nota',
  'note.listeningHint': 'Escuchando… Toca detener cuando termines.',
  'log.customizeWidgetA11y': 'Personalizar el widget de inicio',
  'log.changeAppearanceA11y': 'Cambiar apariencia e idioma',
  'log.openSettingsA11y': 'Abrir ajustes',
  'log.activity': 'Historial',
  'log.filter.all': 'Todo',
  'log.filter.potty': 'Baño',
  'log.filter.meals': 'Comidas',
  'log.filter.walks': 'Paseos',
  'log.filter.naps': 'Siestas',
  'log.filter.other': 'Otro',
  'log.showFilter': 'Mostrar actividad de {filter}',
  'log.showRecentA11y': 'Mostrar actividad de los últimos {count} días',
  'log.viewAllA11y': 'Ver todo el historial, incluidos {count} registros anteriores',
  'log.showRecent': 'Mostrar los últimos {count} días',
  'log.viewAll': 'Ver {count} registros anteriores',
  'log.toggleDayA11y': '{day}, actividades registradas: {count}',
  'log.today': 'Hoy',
  'log.yesterday': 'Ayer',
  'log.emptyTitle': 'Aún no hay actividad',
  'log.emptyRecentTitle': 'No hay actividad reciente en los últimos {count} días',
  'log.emptyFilteredTitle': 'No hay registros de {filter}',
  'log.saveErrorTitle': 'No se pudieron guardar los cambios',
  'log.saveErrorBody': 'Toca el aviso de guardado para reintentar.',
  'log.widgetErrorTitle': 'No se pudo guardar la configuración del widget',
  'log.tryAgain': 'Inténtalo de nuevo.',
  'editor.editNap': 'Editar siesta',
  'editor.editLog': 'Editar registro',
  'editor.close': 'Cerrar editor del registro',
  'editor.retryA11y': 'No se pudieron guardar los cambios. Reintentar ahora',
  'editor.retry': 'No se pudo guardar. Toca para reintentar.',
  'editor.customNameStatus': 'Añade un nombre personalizado para guardar esta actividad.',
  'editor.saving': 'Guardando cambios…',
  'editor.activity': 'ACTIVIDAD',
  'editor.changeActivity': 'Cambiar actividad a {activity}',
  'editor.customName': 'NOMBRE PERSONALIZADO',
  'editor.customNameA11y': 'Nombre de actividad personalizada',
  'editor.customNameHint': 'Obligatorio. Los cambios se guardan automáticamente al escribir.',
  'editor.customPlaceholder': 'p. ej., Cepillado',
  'editor.customInvalid': 'Introduce un nombre para la actividad.',
  'editor.now': 'ahora',
  'editor.inProgress': 'en curso',
  'editor.start': 'INICIO',
  'editor.end': 'FIN',
  'editor.date': 'fecha',
  'editor.time': 'hora',
  'editor.editNapTime': 'Editar hora de {field} de la siesta',
  'editor.quickBackdate': 'REGISTRO RETROACTIVO',
  'editor.setField': 'FIJAR {field}',
  'editor.backdate': 'Fijar la hora hace {count} minutos',
  'editor.setNow': 'Fijar la hora actual',
  'editor.minutesAgo': 'hace {count} min',
  'editor.dateTime': 'FECHA Y HORA',
  'editor.chooseDate': 'Elegir fecha de {field}, actualmente {date}',
  'editor.chooseTime': 'Elegir hora exacta de {field}, actualmente {time}',
  'editor.finishPicker': 'Terminar de elegir {picker}',
  'editor.note': 'NOTA',
  'widget.title': 'Personalizar widget',
  'widget.subtitle': 'Elige entre 2 y 4 acciones.',
  'widget.close': 'Cerrar configuración del widget',
  'widget.addAction': 'Añadir {activity} al widget',
  'widget.removeAction': 'Quitar {activity} del widget',
  'widget.keepTwo': 'Mantén al menos dos acciones en el widget.',
  'widget.removeFirst': 'Quita primero otra acción.',
  'widget.napHint': 'La acción Siesta aparece durante una siesta.',
  'widget.save': 'Guardar configuración del widget',
  'common.saving': 'Guardando…',
  'app.napEnded': 'Siesta terminada',
  'app.napStarted': 'Siesta iniciada',
  'app.logged': '{activity} registrado',
  'app.estimateAdded': '{activity} añadido a la hora estimada',
  'app.deleteTitle': '¿Eliminar este registro?',
  'app.deleteMessage': '{activity} a las {time}',
  'app.cancel': 'Cancelar',
  'app.delete': 'Eliminar',
  'app.routineSaved': 'Rutina guardada',
  'app.notificationsOff': 'Las notificaciones están desactivadas, por lo que no se pudieron programar recordatorios.',
  'app.reminderError': 'Puptime no pudo actualizar los recordatorios. Intenta editar la rutina de nuevo.',
  'schedule.title': 'Rutina',
  'schedule.status.logged': 'Registrado',
  'schedule.status.due': 'Toca ahora',
  'schedule.status.missed': 'Perdido',
  'schedule.status.upcoming': 'Próximo',
  'schedule.saveErrorTitle': 'No se pudo guardar la rutina',
  'schedule.saveErrorBody': 'Tu rutina anterior sigue disponible. Inténtalo de nuevo.',
  'schedule.notificationsOff': 'Las notificaciones están desactivadas',
  'schedule.notificationsBody': 'Permite las notificaciones de Puptime en los ajustes del sistema para usar recordatorios diarios.',
  'schedule.notNow': 'Ahora no',
  'schedule.openSettings': 'Abrir ajustes',
  'schedule.reminderErrorTitle': 'No se pudieron activar los recordatorios',
  'schedule.reminderErrorBody': 'Inténtalo de nuevo desde esta entrada de la rutina.',
  'schedule.removeTitle': '¿Quitar esta hora?',
  'schedule.entryAt': '{activity} a las {time}',
  'schedule.remove': 'Quitar',
  'schedule.removeErrorTitle': 'No se pudo quitar la hora',
  'schedule.removeErrorBody': 'Tu rutina no ha cambiado. Inténtalo de nuevo.',
  'schedule.suggestionErrorTitle': 'No se pudo usar la rutina sugerida',
  'schedule.suggestionErrorBody': 'Tu rutina actual sigue disponible. Inténtalo de nuevo.',
  'schedule.suggestedTimes': '{count} horarios de {days} días registrados',
  'schedule.needDays': 'Faltan {count} días registrados para crear sugerencias',
  'schedule.noPattern': 'Aún no hay un patrón repetido',
  'schedule.previewA11y': 'Previsualizar {count} horas sugeridas para la rutina',
  'schedule.previewButton': 'Revisar sugerencias',
  'schedule.loggedProgress': '{completed} de {total} registrados',
  'schedule.dueOne': 'Hay 1 actividad pendiente ahora',
  'schedule.dueMany': 'Hay {count} actividades pendientes ahora',
  'schedule.missedOne': '1 momento perdido',
  'schedule.missedMany': '{count} momentos perdidos',
  'schedule.everythingLogged': 'Todas las actividades previstas están registradas',
  'schedule.nextAhead': 'La próxima actividad es más tarde',
  'schedule.todayPlan': 'Plan de hoy',
  'schedule.emptyTitle': 'Aún no hay horas',
  'schedule.editA11y': 'Editar {activity} a las {time}, {status}{reminder}',
  'schedule.reminderOn': ', recordatorio diario activado',
  'schedule.removeA11y': 'Quitar {activity} a las {time}',
  'schedule.addA11y': 'Añadir una hora a la rutina',
  'schedule.addTime': 'Añadir una hora',
  'schedule.suggestionTitle': 'Rutina sugerida',
  'schedule.suggestionSubtitle': 'Usa las actividades registradas en la mayoría de {days} días con registros de los últimos {period} días. Las horas se redondean a 15 minutos. No es consejo veterinario.',
  'schedule.closeSuggestion': 'Cerrar rutina sugerida',
  'schedule.replaceCurrent': 'Sustituye tus {count} horas actuales. ',
  'schedule.createRoutine': 'Crea tu rutina. ',
  'schedule.remindersStayOff': 'Los recordatorios empiezan desactivados.',
  'schedule.usingRoutine': 'Aplicando rutina…',
  'schedule.useRoutine': 'Usar esta rutina',
  'schedule.keepRoutine': 'Mantener rutina actual',
  'schedule.editTime': 'Editar hora',
  'schedule.close': 'Cerrar',
  'schedule.activity': 'ACTIVIDAD',
  'schedule.time': 'HORA',
  'schedule.dailyReminder': 'Recordatorio diario',
  'schedule.reminderA11y': 'Recordatorio diario para esta entrada de la rutina',
  'schedule.saveTime': 'Guardar hora',
  'insights.activity': 'actividad',
  'insights.selectedActivity': 'actividad seleccionada',
  'insights.noSelected': 'No hay actividades seleccionadas',
  'insights.allActivity': 'Toda la actividad',
  'insights.timing': 'Horario de {activities}',
  'insights.activityCount': '{count} actividades',
  'insights.pointWindow': '{activity} en la franja de {start} a {end}',
  'insights.durationWindow': '{activity} de aproximadamente {start} a {end}',
  'insights.perDay': '{value}/día',
  'insights.eachRecordedDay': '{count} en cada día registrado',
  'insights.rangePerDay': '{minimum}–{maximum} por día registrado',
  'insights.noLogsYet': 'Aún no hay registros de {activity}',
  'insights.needAnotherLog': 'Hace falta otro registro',
  'insights.middleHalf': 'Mitad central: {lower}–{upper}',
  'insights.gapsObserved': '{count} intervalos observados',
  'insights.logCount': '{count} registros',
  'insights.typicalGap': 'INTERVALO TÍPICO',
  'insights.noLogged': 'No hay registros de {activity}',
  'insights.noActivitySelected': 'No hay actividad seleccionada',
  'insights.today': 'HOY',
  'insights.currentTime': 'Hora actual: {time}',
  'insights.decrease': 'Reducir {control}',
  'insights.increase': 'Aumentar {control}',
  'insights.thisMonth': 'Este mes',
  'insights.monthA11y': '{month}. {average} registros de {activity} por día registrado. {logs} registros en {days} días registrados.',
  'insights.monthDetail': '{logs} registros · {days} días con actividad',
  'insights.exportErrorTitle': 'No se pudo exportar la actividad',
  'insights.exportErrorBody': 'Inténtalo de nuevo. Tus datos de Puptime no han cambiado.',
  'insights.estimateErrorTitle': 'No se pudo añadir esta estimación',
  'insights.estimateErrorBody': 'Tu historial de actividad no ha cambiado. Inténtalo de nuevo.',
  'insights.title': 'Análisis',
  'insights.frequencyTitle': 'Frecuencia',
  'insights.frequencyCaption': '{recorded}/{period} días con registros · no es un objetivo',
  'insights.gapsTitle': 'Posibles ausencias',
  'insights.mealName': 'Comida',
  'insights.around': 'sobre las {time}',
  'insights.aboutRange': 'aprox. {start}–{end}',
  'insights.possibleNap': 'Puede faltar una siesta',
  'insights.mayBeUnlogged': 'Puede faltar {activity}',
  'insights.seenEvidence': 'Registrado cerca de esta hora en {observed} de {compared} días registrados adicionales.',
  'insights.addEstimateA11y': 'Añadir {activity} a la hora estimada',
  'insights.adding': 'Añadiendo…',
  'insights.addLog': 'Añadir registro',
  'insights.needGapDays': 'Faltan {count} días registrados para buscar ausencias.',
  'insights.noGaps': 'No hay ausencias probables en los últimos {count} días.',
  'insights.all': 'Todo',
  'insights.clearFilters': 'Borrar todos los filtros de actividad',
  'insights.selectFilters': 'Seleccionar todos los filtros de actividad',
  'insights.hideTiming': 'Ocultar horario de {activity}',
  'insights.showTiming': 'Mostrar horario de {activity}',
  'insights.panelCaption': '{range} · {count} registros',
  'insights.timeWidth': 'Ancho temporal',
  'insights.dayHeight': 'Días visibles',
  'insights.showEarlier': 'Mostrar fechas anteriores',
  'insights.earlier': 'Anteriores',
  'insights.showNewer': 'Mostrar fechas más recientes',
  'insights.newer': 'Recientes',
  'insights.chooseActivity': 'Elige al menos una actividad arriba para mostrarla en la cronología.',
  'insights.noRangeLogs': 'No hay registros de {activity} en este intervalo.',
  'insights.historyTitle': 'Por mes',
  'insights.showRecentMonths': 'Mostrar meses recientes',
  'insights.showAllMonths': 'Mostrar los {count} meses',
  'insights.exportA11y': 'Exportar toda la actividad como CSV',
  'insights.noExport': 'No hay actividad para exportar',
  'insights.exportHint': 'Abre la hoja para compartir del sistema',
  'insights.preparingExport': 'Preparando exportación…',
  'insights.exportButton': 'Exportar CSV',
  'timeline.title': 'Cronología',
  'timeline.date': 'FECHA',
  'timeline.zoomOut': 'Reducir la escala temporal',
  'timeline.zoomIn': 'Ampliar la escala temporal',
  'timeline.range': '{range} · {count} registros',
  'timeline.loadEarlier': 'Cargar días anteriores',
  'timeline.loadingEarlier': 'Cargando días anteriores',
  'timeline.historyStart': 'No hay días registrados anteriores',
};

const dictionaries: Record<AppLanguage, Dictionary> = {
  en: english,
  'zh-Hans': simplifiedChinese,
  es: spanish,
};

export type TranslationVariables = Record<string, string | number>;

export function isLanguagePreference(value: string | null): value is LanguagePreference {
  return value !== null && languageChoices.includes(value as LanguagePreference);
}

export function resolveLanguage(
  preference: LanguagePreference,
  deviceLocale = Intl.DateTimeFormat().resolvedOptions().locale,
): AppLanguage {
  if (preference !== 'system') return preference;
  const locale = deviceLocale.toLowerCase();
  if (locale.startsWith('zh')) return 'zh-Hans';
  if (locale.startsWith('es')) return 'es';
  return 'en';
}

export function translate(
  language: AppLanguage,
  key: MessageKey,
  variables: TranslationVariables = {},
): string {
  return dictionaries[language][key].replace(/\{(\w+)\}/g, (match, name: string) => (
    Object.prototype.hasOwnProperty.call(variables, name) ? String(variables[name]) : match
  ));
}

const eventKeys: Record<EventType, MessageKey> = {
  pee: 'event.pee',
  poop: 'event.poop',
  meal: 'event.meal',
  pottyTrip: 'event.pottyTrip',
  walk: 'event.walk',
  nap: 'event.nap',
  custom: 'event.custom',
};

const eventPastKeys: Record<EventType, MessageKey> = {
  pee: 'eventPast.pee',
  poop: 'eventPast.poop',
  meal: 'eventPast.meal',
  pottyTrip: 'eventPast.pottyTrip',
  walk: 'eventPast.walk',
  nap: 'eventPast.nap',
  custom: 'eventPast.custom',
};

export function localizedEventLabel(language: AppLanguage, type: EventType): string {
  return translate(language, eventKeys[type]);
}

export function localizedEventPastLabel(language: AppLanguage, event: PuppyEvent): string {
  if (event.type === 'custom' && event.customLabel?.trim()) return event.customLabel.trim();
  if (event.type === 'nap' && event.endedAt === null) return translate(language, 'eventPast.napRunning');
  if (event.type === 'nap' && typeof event.endedAt === 'number') return translate(language, 'eventPast.napped');
  return translate(language, eventPastKeys[event.type]);
}

export function localizedRelativeTime(language: AppLanguage, value: number, now = Date.now()): string {
  const minutes = Math.max(0, Math.floor((now - value) / 60_000));
  if (minutes < 1) return translate(language, 'time.justNow');
  if (minutes < 60) return translate(language, 'time.minutesAgo', { count: minutes });
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return translate(language, 'time.hoursAgo', { count: hours });
  return translate(language, 'time.daysAgo', { count: Math.floor(hours / 24) });
}

export function localizedElapsedTime(language: AppLanguage, value: number, now = Date.now()): string {
  const minutes = Math.max(0, Math.floor((now - value) / 60_000));
  if (minutes < 60) return translate(language, 'time.minutes', { count: minutes });
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return translate(language, 'time.hours', { count: hours });
  return translate(language, 'time.days', { count: Math.floor(hours / 24) });
}
